world: "world"
dimension: "adventure:the_snowbound_isle"
name: "The Snowbound Isle"
sorting: 400
sky-color: "#b0d0ff"
void-color: "#000000"
sky-light: 1
ambient-light: 0.1
min-x: -1024
max-x: 1024
min-z: -1024
max-z: 1024
min-inhabited-time: 1
render-edges: true
enable-perspective-view: false
enable-flat-view: true
enable-free-flight-view: false
enable-hires: false
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
