world: "world"
dimension: "adventure:the_pale_reach"
name: "The Pale Reach"
sorting: 400
sky-color: "#b0d0ff"
void-color: "#000000"
sky-light: 1
ambient-light: 0.1
min-x: -682
max-x: 682
min-z: -682
max-z: 682
min-inhabited-time: 0
render-edges: true
enable-perspective-view: false
enable-flat-view: true
enable-free-flight-view: false
enable-hires: false
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
