world: "world"
dimension: "adventure:the_gauntlet"
name: "The Gauntlet"
sorting: 200
sky-color: "#606060"
void-color: "#000000"
sky-light: 1
ambient-light: 0.1
render-mask: [
  {
    min-x: -2048
    max-x: 2048
    min-z: -2048
    max-z: 2048
  }
]
min-inhabited-time: 1
render-edges: true
enable-perspective-view: false
enable-flat-view: true
enable-free-flight-view: false
enable-hires: false
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
