world: "world"
dimension: "adventure:the_sunken_temple"
name: "The Sunken Temple"
sorting: 400
sky-color: "#b0d0ff"
void-color: "#000000"
sky-light: 1
ambient-light: 0.1
min-x: -8192
max-x: 8192
min-z: -8192
max-z: 8192
min-inhabited-time: 0
render-edges: true
enable-perspective-view: false
enable-flat-view: true
enable-free-flight-view: false
enable-hires: false
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
