world: "world"
dimension: "adventure:the_shallows"
name: "The Shallows"
sorting: 200
sky-color: "#7dabff"
void-color: "#000000"
sky-light: 1
ambient-light: 0.1
render-mask: [
  {
    min-x: -512
    max-x: 512
    min-z: -512
    max-z: 512
  }
]
min-inhabited-time: 1
render-edges: true
enable-perspective-view: false
enable-flat-view: true
enable-free-flight-view: false
enable-hires: false
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
