world: "world"
dimension: "adventure:the_blighted_maw"
name: "The Blighted Maw"
sorting: 300
sky-color: "#290000"
void-color: "#150000"
sky-light: 1
ambient-light: 0.6
min-x: -1024
max-x: 1024
min-z: -1024
max-z: 1024
max-y: 90
min-inhabited-time: 1
render-edges: true
enable-perspective-view: false
enable-flat-view: true
enable-free-flight-view: false
enable-hires: false
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
