world: "world"
dimension: "adventure:the_end_citadel"
name: "The End Citadel"
sorting: 500
sky-color: "#000000"
void-color: "#000000"
sky-light: 0
ambient-light: 0.6
min-x: -8192
max-x: 8192
min-z: -8192
max-z: 8192
min-inhabited-time: 1
render-edges: true
enable-perspective-view: false
enable-flat-view: true
enable-free-flight-view: false
enable-hires: false
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
