# Simple Voice Chat server config. Synced to data/config/voicechat/ on deploy.

port=24454
bind_address=
max_voice_distance=96.0
whisper_distance=24.0
codec=VOIP
mtu_size=1275
tcp_rate_limit=16
keep_alive=1000
enable_groups=true
voice_host=
allow_recording=true
spectator_interaction=false
spectator_player_possession=false
force_voice_chat=false
login_timeout=10000
broadcast_range=-1.0
allow_pings=true
use_natives=true
