#!/usr/bin/env python3
"""seed_paths.py — where the seed roller's own state lives.

One rule: everything the roller derives belongs in <consumer>/.seedtest.
Nothing it derives belongs in data/ (the mc container's tree, deleted to
reset a world) or in .stack/<version>/ (an immutable release directory,
replaced wholesale by the next `./dev update`).

biome_params.json is the case that keeps getting this wrong. It ships in
the bundle as a platform default AND is regenerated by warmup from a real
server boot, so it is both shipped input and derived state. Writing the
regenerated copy back over the shipped one put ~90s of Docker warmup
inside a directory the next update throws away — and, for anyone running
the roller against a checkout, inside the git working tree.

So: read from .seedtest, seeded once from the bundle's copy; write to
.seedtest. The bundle's copy is never modified.
"""
import shutil
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

#: The platform default shipped in the bundle. Read-only.
SHIPPED_BIOME_PARAMS = SCRIPT_DIR / "biome_params.json"


def biome_params_path(seedtest=None):
    """Path to the live biome parameter table.

    With a seedtest directory: <seedtest>/biome_params.json, copied from
    the shipped default on first use so a fresh consumer is immediately
    usable without a Docker warmup. Without one (module demos, tests):
    the shipped copy, unchanged.
    """
    if not seedtest:
        return SHIPPED_BIOME_PARAMS
    live = Path(seedtest) / "biome_params.json"
    if not live.exists() and SHIPPED_BIOME_PARAMS.exists():
        live.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(SHIPPED_BIOME_PARAMS, live)
    return live
