package com.customdimensions.dimension;

import com.customdimensions.MultiverseServer;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * How much ground a structure claims, in blocks, so a castle can be given
 * more room than a well. Generated by scripts/gen-structure-sizes.py from
 * measured {@code StructureStart.getBoundingBox()} spans and baked into the
 * jar as {@code structure_sizes.json}, so no config directory can change what
 * generates.
 *
 * <p>The declared jigsaw fields are not a substitute
 * ([T54](TROUBLESHOOTING.md#t54)). Re-measure with
 * {@code /customdim structure-sizes}; never infer.
 *
 * <p>An id with no measurement takes the table's median, never zero.
 */
public final class StructureFootprints {

    /** The span used when the table is absent entirely, in blocks. */
    public static final int DEFAULT_SPAN = 44;

    /**
     * Bounds on how far a footprint may move a group's exclusion radius.
     * Exclusion also carries the profile's density intent, so size must not
     * dominate it.
     */
    public static final double MIN_SIZE_FACTOR = 0.6;
    public static final double MAX_SIZE_FACTOR = 2.5;

    private static Map<String, Integer> spans;
    private static int medianSpan = DEFAULT_SPAN;

    private StructureFootprints() {
    }

    /** The measured horizontal extent of a structure, in blocks. */
    public static synchronized int spanOf(String structureId) {
        ensureLoaded();
        Integer span = structureId == null ? null : spans.get(structureId);
        return span != null ? span : medianSpan;
    }

    /** Half the span — the radius a placement model reasons with. */
    public static synchronized int radiusOf(String structureId) {
        return spanOf(structureId) / 2;
    }

    /** Whether this id was actually measured, as opposed to taking the median. */
    public static synchronized boolean isMeasured(String structureId) {
        ensureLoaded();
        return structureId != null && spans.containsKey(structureId);
    }

    /** The median span across the table — what an unmeasured structure gets. */
    public static synchronized int median() {
        ensureLoaded();
        return medianSpan;
    }

    public static synchronized int size() {
        ensureLoaded();
        return spans.size();
    }

    /**
     * How much this structure's footprint should scale a group's exclusion
     * radius. Square root of the ratio to the median: exclusion is a radius,
     * a footprint is area-like. Bounded by
     * {@link #MIN_SIZE_FACTOR}/{@link #MAX_SIZE_FACTOR}.
     */
    public static synchronized double sizeFactor(String structureId) {
        ensureLoaded();
        int span = spanOf(structureId);
        if (span <= 0 || medianSpan <= 0) {
            return 1.0;
        }
        double factor = Math.sqrt((double) span / medianSpan);
        return Math.max(MIN_SIZE_FACTOR, Math.min(MAX_SIZE_FACTOR, factor));
    }

    /**
     * The footprint function for one group's pool: at any chunk, the size
     * factor of the structure {@link StructurePick} assigns there. Both halves
     * are pure functions of the chunk, which keeps placement order-free.
     *
     * <p>Null for an empty pool, which {@link NoiseFieldIndex} answers with
     * the uniform path.
     */
    public static NoiseFieldIndex.Footprints forPool(
            long noiseSeed, List<StructurePick.PoolEntry> sortedPool) {
        if (sortedPool == null || sortedPool.isEmpty()) {
            return null;
        }
        return (chunkX, chunkZ) -> sizeFactor(
                StructurePick.assignedStructure(noiseSeed, chunkX, chunkZ, sortedPool));
    }

    /**
     * The first candidate in a site's chain whose declared biomes accept the
     * biome there — the same walk the selection mixin makes at generation
     * time. Sampled at y=64.
     */
    public static NoiseFieldIndex.Occupants occupantsFor(
            long noiseSeed, List<StructurePick.PoolEntry> sortedPool,
            net.minecraft.world.biome.source.BiomeSource biomeSource,
            net.minecraft.world.gen.noise.NoiseConfig noiseConfig) {
        if (sortedPool == null || sortedPool.isEmpty()
                || biomeSource == null || noiseConfig == null) {
            return null;
        }
        Map<String, Integer> ordinal = new HashMap<>();
        for (int i = 0; i < sortedPool.size(); i++) {
            ordinal.putIfAbsent(sortedPool.get(i).structureId(), i);
        }
        final int quartY = 16;   // block y 64
        return (chunkX, chunkZ) -> {
            int blockX = chunkX * 16 + 8;
            int blockZ = chunkZ * 16 + 8;
            net.minecraft.registry.entry.RegistryEntry<net.minecraft.world.biome.Biome> biome;
            try {
                biome = biomeSource.getBiome(blockX >> 2, quartY, blockZ >> 2,
                        noiseConfig.getMultiNoiseSampler());
            } catch (RuntimeException e) {
                return -1;
            }
            if (biome == null) {
                return -1;
            }
            for (StructurePick.PoolEntry candidate : StructurePick.candidates(sortedPool,
                    StructurePick.pickValue(noiseSeed, chunkX, chunkZ),
                    StructurePick.MAX_CANDIDATES)) {
                if (accepts(candidate, biome)) {
                    Integer i = ordinal.get(candidate.structureId());
                    return i == null ? -1 : i;
                }
            }
            return -1;
        };
    }

    /** Whether this candidate's own declared biomes admit that biome. */
    private static boolean accepts(
            StructurePick.PoolEntry candidate,
            net.minecraft.registry.entry.RegistryEntry<net.minecraft.world.biome.Biome> biome) {
        if (candidate.bypassBiome()) {
            return true;
        }
        if (candidate.structure() == null) {
            return false;
        }
        try {
            return candidate.structure().value().getValidBiomes().contains(biome);
        } catch (RuntimeException e) {
            return false;
        }
    }

    /** Test seam: forces the next lookup to re-read from the jar. */
    static synchronized void reset() {
        spans = null;
        medianSpan = DEFAULT_SPAN;
    }

    /** Test seam: install a table directly, bypassing the jar resource. */
    static synchronized void install(Map<String, Integer> table) {
        spans = Map.copyOf(table);
        medianSpan = medianOf(spans.values());
    }

    private static void ensureLoaded() {
        if (spans == null) {
            spans = load();
            medianSpan = spans.isEmpty() ? DEFAULT_SPAN : medianOf(spans.values());
        }
    }

    private static Map<String, Integer> load() {
        try (InputStream in =
                     StructureFootprints.class.getResourceAsStream("/structure_sizes.json")) {
            if (in == null) {
                MultiverseServer.LOGGER.warn(
                        "structure_sizes.json missing from jar — every structure will take the "
                        + "default span of {} blocks", DEFAULT_SPAN);
                return Collections.emptyMap();
            }
            Map<String, JsonElement> raw = new Gson().fromJson(
                    new InputStreamReader(in, StandardCharsets.UTF_8),
                    new TypeToken<Map<String, JsonElement>>() {
                    }.getType());
            Map<String, Integer> parsed = parse(raw);
            MultiverseServer.LOGGER.info("Loaded {} structure footprints (median span {} blocks)",
                    parsed.size(), parsed.isEmpty() ? DEFAULT_SPAN : medianOf(parsed.values()));
            return parsed;
        } catch (Exception e) {
            MultiverseServer.LOGGER.error("Failed to load structure_sizes.json", e);
            return Collections.emptyMap();
        }
    }

    /**
     * Reads the generator's {@code {"structures": {"<id>": {"span": N}}}}
     * shape. An entry missing a usable span is skipped rather than defaulted,
     * so it reports as unmeasured and takes the median like any other absence.
     */
    private static Map<String, Integer> parse(Map<String, JsonElement> raw) {
        if (raw == null) {
            return Collections.emptyMap();
        }
        JsonElement structures = raw.get("structures");
        if (structures == null || !structures.isJsonObject()) {
            return Collections.emptyMap();
        }
        Map<String, Integer> out = new HashMap<>();
        for (Map.Entry<String, JsonElement> e : structures.getAsJsonObject().entrySet()) {
            if (!e.getValue().isJsonObject()) {
                continue;
            }
            JsonObject row = e.getValue().getAsJsonObject();
            if (!row.has("span")) {
                continue;
            }
            try {
                int span = row.get("span").getAsInt();
                if (span > 0) {
                    out.put(e.getKey(), span);
                }
            } catch (RuntimeException ignored) {
                // A malformed row is one unmeasured structure, not a boot failure.
            }
        }
        return Map.copyOf(out);
    }

    private static int medianOf(java.util.Collection<Integer> values) {
        if (values.isEmpty()) {
            return DEFAULT_SPAN;
        }
        List<Integer> sorted = new ArrayList<>(values);
        Collections.sort(sorted);
        return sorted.get(sorted.size() / 2);
    }
}
