package com.customdimensions.dimension;

import com.customdimensions.MultiverseServer;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Answers "which noise group does this structure set belong to, how rare is
 * it, and what should this world type do with that group" — the data half of
 * noise placement.
 *
 * Two sources, both jar-baked so a stale or seed-reverted config directory can
 * never change worldgen (the self-containment rule in mods/AGENTS.md):
 *
 * <ul>
 * <li>{@code structure_themes.json} — per-set theme/group/rarity, generated by
 *     scripts/gen-structure-groups.py, read via {@link StructureThemes} (which
 *     also merges a consumer overlay).</li>
 * <li>{@code structure_type_defaults.json} — per-world-type enabled groups,
 *     profile and radial overrides, named curves, rarity shares and the
 *     difficulty shifts. Hand-authored as
 *     config/custom-dimensions/structure-type-defaults.json and mirrored into
 *     the jar by the same generator.</li>
 * </ul>
 *
 * Sets neither file knows about are classified from their live placement:
 * {@code deco} (the least opinionated group — natural profile, even radial)
 * with a rarity derived from the same spacing thresholds the generator uses.
 * Every auto-classification is logged once at INFO, and
 * {@code /customdim structure-audit} lists every set with the source it came
 * from.
 */
public final class StructureGroupRegistry {

    /** Where a classification came from, for the audit command. */
    public enum Source {
        /** Baked map or consumer overlay. */
        REGISTRY,
        /** Derived from the set's live placement spacing. */
        INFERRED
    }

    public record Entry(String setId, String theme, String group, String rarity, Source source) {
    }

    private static final String UNKNOWN_GROUP = "deco";

    private static TypeDefaults defaults;
    private static final Map<String, Entry> INFERRED = new ConcurrentHashMap<>();

    private StructureGroupRegistry() {
    }

    // ------------------------------------------------------------------
    // Per-set classification
    // ------------------------------------------------------------------

    /**
     * Classifies a structure set.
     *
     * @param setId   structure SET id, or null for an unkeyed set
     * @param spacing the set's placement spacing in chunks, or -1 when it is
     *                not a random-spread placement (inference then falls back
     *                to the middle tier rather than pretending to know)
     */
    public static Entry classify(String setId, int spacing) {
        if (setId == null) {
            return new Entry(null, null, UNKNOWN_GROUP, rarityForSpacing(spacing), Source.INFERRED);
        }
        StructureThemes.Classification known = StructureThemes.classificationOf(setId);
        if (known != null && known.group() != null) {
            String rarity = known.rarity() != null ? known.rarity() : rarityForSpacing(spacing);
            return new Entry(setId, known.theme(), known.group(), rarity, Source.REGISTRY);
        }
        // Unknown, or a legacy theme-only overlay row with no rarity.
        String theme = known != null ? known.theme() : null;
        String group = known != null && known.group() != null ? known.group() : UNKNOWN_GROUP;
        Entry entry = new Entry(setId, theme, group, rarityForSpacing(spacing), Source.INFERRED);
        Entry previous = INFERRED.putIfAbsent(setId, entry);
        if (previous == null) {
            MultiverseServer.LOGGER.info(
                    "Auto-classified structure set {} as group={} rarity={} (spacing {}) — "
                    + "add it to overlay/config/structure_themes.json to classify it yourself",
                    setId, entry.group(), entry.rarity(), spacing < 0 ? "n/a" : spacing);
        }
        return entry;
    }

    public static String groupOf(String setId, int spacing) {
        return classify(setId, spacing).group();
    }

    public static String rarityOf(String setId, int spacing) {
        return classify(setId, spacing).rarity();
    }

    /**
     * Spacing to rarity tier.
     *
     * MIRRORED from rarity_for() in scripts/gen-structure-groups.py and
     * scripts/seed/structure_placement.py — change all three together. A
     * negative spacing means "not a random-spread placement", which lands on
     * `uncommon`: the middle tier, so an unclassifiable set neither floods
     * its group nor vanishes from it.
     */
    public static String rarityForSpacing(int spacing) {
        if (spacing < 0) {
            return "uncommon";
        }
        if (spacing > 80) {
            return "endgame";
        }
        if (spacing > 45) {
            return "rare";
        }
        if (spacing > 24) {
            return "uncommon";
        }
        return "common";
    }

    /** Everything auto-classified so far, for the audit command. */
    public static List<Entry> inferred() {
        List<Entry> out = new ArrayList<>(INFERRED.values());
        out.sort(java.util.Comparator.comparing(Entry::setId));
        return out;
    }

    // ------------------------------------------------------------------
    // Type defaults
    // ------------------------------------------------------------------

    /** Parsed structure_type_defaults.json. */
    public record TypeDefaults(Map<String, double[]> curves,
                               Map<String, GroupDefault> groupDefaults,
                               Map<String, Double> rarityShares,
                               Map<String, TypeEntry> types,
                               double hostileMinMobMultiplier,
                               Map<String, String> hostileRadial,
                               double peacefulMaxMobMultiplier,
                               Map<String, String> peacefulProfiles,
                               Map<String, String> terrainAdaptation) {
    }

    /**
     * Theme (group) -> terrain-adaptation defaults, applied to structures
     * whose registry value is "none" (TerrainAdaptationOverride). Empty when
     * the jar table carries no block.
     */
    public static Map<String, String> terrainAdaptationDefaults() {
        return defaults().terrainAdaptation();
    }

    public record GroupDefault(String profile, String radial, int exclusion) {
    }

    public record TypeEntry(List<String> groups,
                            Map<String, String> profiles,
                            Map<String, String> radial) {
    }

    public static synchronized TypeDefaults defaults() {
        if (defaults == null) {
            defaults = loadDefaults();
        }
        return defaults;
    }

    /** Test seam: forces the next call to re-read from the jar. */
    static synchronized void reset() {
        defaults = null;
        INFERRED.clear();
    }

    /** Groups a world type enables, in file order. Unknown types get none. */
    public static List<String> groupsForType(String worldType) {
        TypeEntry entry = defaults().types().get(worldType == null ? "" : worldType);
        return entry == null ? List.of() : entry.groups();
    }

    public static GroupDefault groupDefault(String group) {
        return defaults().groupDefaults().get(group);
    }

    public static double[] curve(String name) {
        return defaults().curves().get(name);
    }

    /** Relative weight of a rarity tier within its group. */
    public static double rarityShare(String rarity) {
        Double share = defaults().rarityShares().get(rarity);
        return share != null ? share : 1.0;
    }

    private static TypeDefaults loadDefaults() {
        try (InputStream in = StructureGroupRegistry.class
                .getResourceAsStream("/structure_type_defaults.json")) {
            if (in == null) {
                MultiverseServer.LOGGER.error(
                        "structure_type_defaults.json missing from jar — noise placement "
                        + "disabled, dimensions keep vanilla grid placement");
                return empty();
            }
            JsonObject root = new Gson().fromJson(
                    new InputStreamReader(in, StandardCharsets.UTF_8), JsonObject.class);
            return parse(root);
        } catch (Exception e) {
            MultiverseServer.LOGGER.error(
                    "Failed to load structure_type_defaults.json — noise placement disabled", e);
            return empty();
        }
    }

    private static TypeDefaults empty() {
        return new TypeDefaults(Map.of(), Map.of(), Map.of(), Map.of(),
                Double.MAX_VALUE, Map.of(), -1.0, Map.of(), Map.of());
    }

    private static TypeDefaults parse(JsonObject root) {
        Map<String, double[]> curves = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("curves").entrySet()) {
            var array = e.getValue().getAsJsonArray();
            double[] curve = new double[array.size()];
            for (int i = 0; i < curve.length; i++) {
                curve[i] = array.get(i).getAsDouble();
            }
            curves.put(e.getKey(), curve);
        }

        Map<String, GroupDefault> groupDefaults = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("groupDefaults").entrySet()) {
            JsonObject o = e.getValue().getAsJsonObject();
            groupDefaults.put(e.getKey(), new GroupDefault(
                    o.get("profile").getAsString(),
                    o.get("radial").getAsString(),
                    o.get("exclusion").getAsInt()));
        }

        Map<String, Double> shares = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("rarityShares").entrySet()) {
            shares.put(e.getKey(), e.getValue().getAsDouble());
        }

        Map<String, TypeEntry> types = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("types").entrySet()) {
            JsonObject o = e.getValue().getAsJsonObject();
            List<String> groups = new ArrayList<>();
            for (JsonElement g : o.getAsJsonArray("groups")) {
                groups.add(g.getAsString());
            }
            types.put(e.getKey(), new TypeEntry(
                    List.copyOf(groups),
                    stringMap(o.getAsJsonObject("profiles")),
                    stringMap(o.getAsJsonObject("radial"))));
        }

        JsonObject shifts = root.getAsJsonObject("difficultyShifts");
        JsonObject hostile = shifts.getAsJsonObject("hostile");
        JsonObject peaceful = shifts.getAsJsonObject("peaceful");

        return new TypeDefaults(
                Collections.unmodifiableMap(curves),
                Collections.unmodifiableMap(groupDefaults),
                Collections.unmodifiableMap(shares),
                Collections.unmodifiableMap(types),
                hostile.get("minMobMultiplier").getAsDouble(),
                stringMap(hostile.getAsJsonObject("radial")),
                peaceful.get("maxMobMultiplier").getAsDouble(),
                stringMap(peaceful.getAsJsonObject("profiles")),
                stringMap(root.getAsJsonObject("terrainAdaptation")));
    }

    private static Map<String, String> stringMap(JsonObject o) {
        if (o == null) {
            return Map.of();
        }
        Map<String, String> out = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : o.entrySet()) {
            out.put(e.getKey(), e.getValue().getAsString());
        }
        return Collections.unmodifiableMap(out);
    }

    /** Every group name the registry knows, in a stable order. */
    public static Set<String> knownGroups() {
        return Collections.unmodifiableSet(new LinkedHashSet<>(defaults().groupDefaults().keySet()));
    }
}
