package com.customdimensions.dimension;

import com.customdimensions.MultiverseServer;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * How much ground a structure claims, in blocks, so a castle can be given
 * more room than a well.
 *
 * <p>Generated by scripts/gen-structure-sizes.py from measured
 * {@code StructureStart.getBoundingBox()} spans and baked into the jar as
 * {@code structure_sizes.json}. Jar-baked for the reason every worldgen table
 * here is: a stale or seed-reverted config directory must never be able to
 * change what generates.
 *
 * <p><b>The declared jigsaw fields are not a substitute
 * ([T54](TROUBLESHOOTING.md#t54)).</b> Measured against the real boxes, {@code
 * size} correlates at Spearman +0.478 and {@code max_distance_from_center} at
 * +0.357 — a declared size of 1 spans 5 to 72 blocks in practice. Re-measure
 * with {@code /customdim structure-sizes}; never infer.
 *
 * <p><b>A missing structure is not a zero.</b> An id with no measurement falls
 * back to the median of the whole table, because zero would silently grant it
 * no personal space at all — the failure that looks like the feature working.
 */
public final class StructureFootprints {

    /**
     * The span used when the table is absent entirely, in blocks. The measured
     * median across 781 structures is 44; this is that, so a jar shipped
     * without the resource behaves like the middle of the pack rather than
     * like nothing.
     */
    public static final int DEFAULT_SPAN = 44;

    /**
     * Bounds on how far a footprint may move a group's exclusion radius.
     * A structure ten times the median must claim more ground than one a
     * tenth of it, but not ten times more: exclusion also carries the
     * profile's density intent, and letting size dominate it would make
     * `dense` mean nothing wherever the pool happens to hold a big structure.
     */
    public static final double MIN_SIZE_FACTOR = 0.6;
    public static final double MAX_SIZE_FACTOR = 2.5;

    private static Map<String, Integer> spans;
    private static int medianSpan = DEFAULT_SPAN;

    private StructureFootprints() {
    }

    /** The measured horizontal extent of a structure, in blocks. */
    public static synchronized int spanOf(String structureId) {
        ensureLoaded();
        Integer span = structureId == null ? null : spans.get(structureId);
        return span != null ? span : medianSpan;
    }

    /** Half the span — the radius a placement model reasons with. */
    public static synchronized int radiusOf(String structureId) {
        return spanOf(structureId) / 2;
    }

    /** Whether this id was actually measured, as opposed to taking the median. */
    public static synchronized boolean isMeasured(String structureId) {
        ensureLoaded();
        return structureId != null && spans.containsKey(structureId);
    }

    /** The median span across the table — what an unmeasured structure gets. */
    public static synchronized int median() {
        ensureLoaded();
        return medianSpan;
    }

    public static synchronized int size() {
        ensureLoaded();
        return spans.size();
    }

    /**
     * How much this structure's footprint should scale a group's exclusion
     * radius, bounded by {@link #MIN_SIZE_FACTOR}/{@link #MAX_SIZE_FACTOR}.
     *
     * <p>The square root of the ratio to the median, not the ratio itself:
     * exclusion is a radius and a footprint is an area-like quantity, so a
     * structure four times the median's span should claim about twice the
     * separation, not four times. Without the root, the measured 1-to-256
     * span range drives a 256x spread in separation and the profile's own
     * density intent stops meaning anything.
     */
    public static synchronized double sizeFactor(String structureId) {
        ensureLoaded();
        int span = spanOf(structureId);
        if (span <= 0 || medianSpan <= 0) {
            return 1.0;
        }
        double factor = Math.sqrt((double) span / medianSpan);
        return Math.max(MIN_SIZE_FACTOR, Math.min(MAX_SIZE_FACTOR, factor));
    }

    /** Test seam: forces the next lookup to re-read from the jar. */
    static synchronized void reset() {
        spans = null;
        medianSpan = DEFAULT_SPAN;
    }

    /** Test seam: install a table directly, bypassing the jar resource. */
    static synchronized void install(Map<String, Integer> table) {
        spans = Map.copyOf(table);
        medianSpan = medianOf(spans.values());
    }

    private static void ensureLoaded() {
        if (spans == null) {
            spans = load();
            medianSpan = spans.isEmpty() ? DEFAULT_SPAN : medianOf(spans.values());
        }
    }

    private static Map<String, Integer> load() {
        try (InputStream in =
                     StructureFootprints.class.getResourceAsStream("/structure_sizes.json")) {
            if (in == null) {
                MultiverseServer.LOGGER.warn(
                        "structure_sizes.json missing from jar — every structure will take the "
                        + "default span of {} blocks", DEFAULT_SPAN);
                return Collections.emptyMap();
            }
            Map<String, JsonElement> raw = new Gson().fromJson(
                    new InputStreamReader(in, StandardCharsets.UTF_8),
                    new TypeToken<Map<String, JsonElement>>() {
                    }.getType());
            Map<String, Integer> parsed = parse(raw);
            MultiverseServer.LOGGER.info("Loaded {} structure footprints (median span {} blocks)",
                    parsed.size(), parsed.isEmpty() ? DEFAULT_SPAN : medianOf(parsed.values()));
            return parsed;
        } catch (Exception e) {
            MultiverseServer.LOGGER.error("Failed to load structure_sizes.json", e);
            return Collections.emptyMap();
        }
    }

    /**
     * Reads the generator's {@code {"structures": {"<id>": {"span": N}}}}
     * shape. An entry missing a usable span is skipped rather than defaulted,
     * so it reports as unmeasured and takes the median like any other absence.
     */
    private static Map<String, Integer> parse(Map<String, JsonElement> raw) {
        if (raw == null) {
            return Collections.emptyMap();
        }
        JsonElement structures = raw.get("structures");
        if (structures == null || !structures.isJsonObject()) {
            return Collections.emptyMap();
        }
        Map<String, Integer> out = new HashMap<>();
        for (Map.Entry<String, JsonElement> e : structures.getAsJsonObject().entrySet()) {
            if (!e.getValue().isJsonObject()) {
                continue;
            }
            JsonObject row = e.getValue().getAsJsonObject();
            if (!row.has("span")) {
                continue;
            }
            try {
                int span = row.get("span").getAsInt();
                if (span > 0) {
                    out.put(e.getKey(), span);
                }
            } catch (RuntimeException ignored) {
                // A malformed row is one unmeasured structure, not a boot failure.
            }
        }
        return Map.copyOf(out);
    }

    private static int medianOf(java.util.Collection<Integer> values) {
        if (values.isEmpty()) {
            return DEFAULT_SPAN;
        }
        List<Integer> sorted = new ArrayList<>(values);
        Collections.sort(sorted);
        return sorted.get(sorted.size() / 2);
    }
}
