#!/usr/bin/env bash
# deploy.sh - The production deploy. Runs ON the server from the stack bundle;
# CI invokes it for every "full" deploy (see deploy-reusable.yml).
#
# Sequence: in-game countdown (60s->1s) -> clear whitelist (blocks joins) ->
# kick all -> save-all flush -> stop mc -> pull images -> re-run seed ->
# seed mod configs into data/config/ -> apply overlay -> datapacks ->
# BlueMap defaults (pre-boot, no reload) -> enforce Discord config ->
# Modrinth sync IF mod list changed -> compose up -> force-recreate sidecars ->
# wait for RCON (180s) -> world borders -> game rules -> LuckPerms -> spawn ->
# restore whitelist -> welcome back -> docker prune.
#
# Usage:
#   .stack/current/stack/scripts/deploy.sh                    # restart only
#   .stack/current/stack/scripts/deploy.sh --non-interactive  # for CI
#
# The server directory layout (~/server/) is:
#   .env            - generated by CI on every full deploy
#   overlay/        - rsynced from consumer repo by CI
#   cloudflared/    - host-generated tunnel config
#   .stack/current/ - stack bundle cache (via stack-pull.sh)
#   modpack-dist/   - built pack output
#   data/           - world state
#
# Gotchas:
#   - Don't run while CI is deploying (races).
#   - The force-recreate sidecar list below must match infra-deploy.sh.
#   - Game rules here must match config/boring_default_game_rules/config.json.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

# STACK_DIR = the bundle root (where compose files + scripts + config live).
# SERVER_DIR = the server root (where .env, data/, overlay/ live).
STACK_DIR="$PROJECT_DIR"
if [[ "$SCRIPT_DIR" == *"/.stack/"* ]]; then
  SERVER_DIR="${SCRIPT_DIR%%/.stack/*}"
else
  SERVER_DIR="${SERVER_DIR:-$PROJECT_DIR}"
fi
cd "$SERVER_DIR"

COMPOSE_FILE="$STACK_DIR/docker-compose.yml"

# --- deploy banner ----------------------------------------------------------
# Printed BEFORE the timestamp redirect so ASCII art stays clean. Consumers
# personalise it by shipping overlay/config/deploy-banner.txt (any multiline
# art); the bundle's config/deploy-banner.txt is the default. CI passes
# DEPLOY_COMMIT so the status line identifies exactly what is going out.
BUNDLE_VERSION="v$(cat "$STACK_DIR/VERSION" 2> /dev/null || echo '?')"
BANNER_FILE="$SERVER_DIR/overlay/config/deploy-banner.txt"
[[ -f "$BANNER_FILE" ]] || BANNER_FILE="$STACK_DIR/config/deploy-banner.txt"
# if/fi, not `[[ ]] &&`: a missing banner must not kill the deploy (set -e)
if [[ -f "$BANNER_FILE" ]]; then cat "$BANNER_FILE"; fi
echo "  ${BRAND_NAME:-Minecraft} — deploying stack ${BUNDLE_VERSION} | mc ${MC_VERSION:-1.21.1} | $(date '+%Y-%m-%d %H:%M %Z')${DEPLOY_COMMIT:+ | commit ${DEPLOY_COMMIT}}"
echo ""

# --- timestamped output ---------------------------------------------------
# Deploys are long and the captured log is the primary forensic artefact:
# stamp every line with wall-clock time. Child scripts (setup-dimensions,
# setup-permissions) inherit stdout, so their output is stamped too.
# printf %(...)T needs bash >= 4.2 — fine, deploy.sh only ever runs on the
# Linux server (see header), never on a macOS workstation.
exec > >(while IFS= read -r line; do printf '[%(%H:%M:%S)T] %s\n' -1 "$line"; done) 2>&1

echo "==> deploy.sh starting (stack bundle ${BUNDLE_VERSION})"

# --- load .env ----------------------------------------------------------------
if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

# --- flags --------------------------------------------------------------------
export NON_INTERACTIVE=0
QUICK=0
for arg in "$@"; do
  case "$arg" in
    --non-interactive) export NON_INTERACTIVE=1 ;;
    --quick) QUICK=1 ;;
  esac
done

# --- bind-mount targets -----------------------------------------------------
# These must exist BEFORE any compose command: Docker creates missing
# bind-mount paths as root, so if a sidecar (e.g. mod-checker's read-only
# ./data/mods mount) starts first, mc (uid 1000) can't write its mods and
# crash-loops with AccessDeniedException.
mkdir -p "$SERVER_DIR/data/mods" "$SERVER_DIR/data/config" \
  "$SERVER_DIR/modpack-dist" "$SERVER_DIR/overlay" \
  "$SERVER_DIR/backups" "$SERVER_DIR/cloudflared"

# --- Suspend autopause for the whole deploy -----------------------------------
# Boot takes minutes with many dimensions and AUTOPAUSE_TIMEOUT_INIT is 120s:
# without this, the daemon pauses the JVM BETWEEN the deploy's own RCON
# commands and every next command has to knock it awake — activation crawls
# and the pause/resume churn races the chunk system. The autopause daemon
# honours only /data/.skip-pause, so that file is a derived AGGREGATE:
# deploy.sh owns .skip-pause-deploying, idle-tasks owns .skip-pause-idle,
# and the aggregate exists iff any owner file exists — each owner cleans
# up its own suspension without clobbering the other's. Managed via
# docker exec (the host uid can't write container-owned paths). Applied
# here (if mc is up) and re-applied after the restart in step 11;
# released on exit.
suspend_autopause() {
  docker exec mc sh -c 'touch /data/.skip-pause-deploying /data/.skip-pause' 2> /dev/null || true
}
resume_autopause() {
  docker exec mc sh -c 'rm -f /data/.skip-pause-deploying; [ -e /data/.skip-pause-idle ] || rm -f /data/.skip-pause' 2> /dev/null || true
}
suspend_autopause
trap resume_autopause EXIT

# --- helpers ------------------------------------------------------------------
# Hard 30s cap per RCON call: a single hung command (e.g. a wedged main
# thread) must fail the step, never freeze the whole deploy — an unbounded
# rcon call once pinned a deploy for 50+ minutes against a deadlocked server.
# Each call also heartbeats the deploy sentinel: idle-tasks goes dormant
# while .skip-pause-deploying exists but treats a stale mtime (default
# >60min) as a dead deploy and cleans it up — the touch keeps hours-long
# dimension passes recognised as live.
rcon() {
  docker exec mc sh -c 'touch /data/.skip-pause-deploying' 2> /dev/null || true
  timeout 30 docker exec mc rcon-cli "$@" 2> /dev/null || true
}

# Kuma maintenance window for the whole deploy: monitors show "maintenance"
# instead of flapping up/down (and Kuma's Discord alerts stay quiet) while
# we restart things. Runs the helper inside the kuma-init image (has
# uptime-kuma-api + auth env from compose); --no-deps because uptime-kuma
# is already up (or down, in which case this must not block the deploy).
kuma_maintenance() {
  # shellcheck disable=SC2086
  timeout 60 docker compose --project-directory "$SERVER_DIR" -f "$COMPOSE_FILE" --profile cloud \
    run --rm --no-deps kuma-init python3 /app/kuma-maintenance.py "$1" 2> /dev/null || true
}
kuma_maintenance start

# mc-backup must not run mid-deploy: its scheduled rcon save-on/save-off
# fires against a stopped or booting server (5x ERROR retries per attempt)
# and a backup of a half-assembled deploy state is worthless. Stopped here
# and RE-stopped after every compose up below (which would otherwise start
# it again); resumed by the EXIT trap. If a deploy dies without the trap,
# idle-tasks' stale-sentinel cleanup restarts it.
pause_backups() {
  docker stop mc-backup 2> /dev/null || true
}
resume_backups() {
  docker start mc-backup 2> /dev/null || true
}
pause_backups

# Replaces the earlier resume-only trap: close the maintenance window,
# release the autopause suspension, and restart backups however the
# deploy exits.
trap 'kuma_maintenance stop; resume_autopause; resume_backups' EXIT

msg() {
  local key="$1"
  local messages_file="$SERVER_DIR/overlay/config/messages.json"
  [[ -f "$messages_file" ]] || messages_file="$STACK_DIR/config/messages.json"
  python3 -c "import json; print(json.load(open('$messages_file'))['$key'])" 2> /dev/null || echo "$key"
}

server_alive() {
  docker exec mc rcon-cli "list" &> /dev/null 2>&1
}

get_player_count() {
  local result
  result=$(timeout 30 docker exec mc rcon-cli "list" 2> /dev/null || echo "")
  if [[ -z "$result" ]]; then
    echo "0"
    return
  fi
  echo "$result" | grep -oE 'There are [0-9]+' | grep -oE '[0-9]+' || echo "0"
}

# =============================================================================
# 1. In-game countdown warnings
# =============================================================================
if server_alive; then
  # Empty server = no one to warn: skip the 60s countdown (and its Discord
  # chat-bridge spam) and restart immediately, exactly like --quick.
  if [[ $QUICK -eq 0 ]] && [[ "$(get_player_count)" -eq 0 ]]; then
    echo "==> No players online - skipping countdown"
    QUICK=1
  fi
  if [[ $QUICK -eq 0 ]]; then
    echo "==> Sending in-game restart warnings..."

    rcon "say $(msg restart.warning_60s)"
    echo "  60s warning sent"
    sleep 30

    rcon "say $(msg restart.warning_30s)"
    echo "  30s warning sent"
    sleep 20

    rcon "say $(msg restart.warning_10s)"
    echo "  10s warning sent"
    sleep 5

    rcon "say $(msg restart.warning_5s)"
    sleep 2
    rcon "say $(msg restart.countdown_3)"
    sleep 1
    rcon "say $(msg restart.countdown_2)"
    sleep 1
    rcon "say $(msg restart.countdown_1)"
    sleep 1
  else
    echo "==> Quick restart (skipping countdown)..."
    rcon "say $(msg restart.now)"
    sleep 1
  fi

  # =========================================================================
  # 2. Block new connections
  # =========================================================================
  echo ""
  echo "==> Blocking new connections..."
  rcon "whitelist off"
  rcon "whitelist on"
  echo "  New connections blocked (whitelist cleared)"

  # =========================================================================
  # 3. Kick all connected players
  # =========================================================================
  echo "==> Disconnecting all players..."
  rcon "kick @a $(msg restart.kick)"

  sleep 2

  KICK_WAIT=0
  while [[ $(get_player_count) -gt 0 && $KICK_WAIT -lt 30 ]]; do
    echo "  Waiting for players to disconnect..."
    sleep 2
    KICK_WAIT=$((KICK_WAIT + 2))
  done

  REMAINING=$(get_player_count)
  if [[ "$REMAINING" -gt 0 ]]; then
    echo "  Warning: $REMAINING players still connected after 30s"
    rcon "kick @a $(msg restart.kick_forced)"
    sleep 2
  fi
  echo "  All players disconnected"

  # =========================================================================
  # 4. Quiet-boot gamerules + save and flush (world is now quiesced)
  # =========================================================================
  # Gamerules persist in level.dat, so setting these BEFORE the stop means
  # the NEXT boot runs with spawning/ticking/cycles off — nobody is online
  # during a deploy, and dimension activation gets dramatically cheaper
  # (entity spawn + game-event work during chunk loads is what blocks the
  # main thread). Restored by step 14's "Enforcing game rules" at the end.
  echo ""
  echo "==> Enabling quiet-boot mode (spawning/ticking off until deploy completes)..."
  rcon "gamerule doMobSpawning false"
  rcon "gamerule randomTickSpeed 0"
  rcon "gamerule doDaylightCycle false"
  rcon "gamerule doWeatherCycle false"
  rcon "gamerule doFireTick false"

  echo ""
  echo "==> Saving world..."
  rcon "save-off"
  rcon "save-all flush"
  sleep 5
  echo "  World saved and flushed"

  rcon "save-on"

  # =========================================================================
  # 5. Stop the mc container cleanly
  # =========================================================================
  echo ""
  echo "==> Stopping Minecraft server..."
  docker compose --project-directory "$SERVER_DIR" -f "$COMPOSE_FILE" stop mc 2> /dev/null \
    || docker compose stop mc 2> /dev/null || true
  echo "  Server stopped"

else
  echo "  Server not responding to RCON, skipping warnings/kick."
fi

# =============================================================================
# 6. Pull Docker images (pinned to the stack version when set)
# =============================================================================
# IMAGE_TAG defaults to `latest` in docker-compose.yml. When STACK_VERSION
# is set (it always is on production — CI writes it to .env), derive the
# tag from it so images match the bundle: STACK_VERSION=v2.13.0 → tag 2.13.0,
# STACK_VERSION=v2 → tag 2. Release.yml tags every image with major, minor,
# and patch semver patterns, so any pin depth resolves.
if [[ -n "${STACK_VERSION:-}" && -z "${IMAGE_TAG:-}" ]]; then
  export IMAGE_TAG="${STACK_VERSION#v}"
fi
echo ""
echo "==> Pulling Docker images (tag: ${IMAGE_TAG:-latest})..."
docker compose --project-directory "$SERVER_DIR" -f "$COMPOSE_FILE" --profile cloud pull

# =============================================================================
# 7. Re-run seed container (overlay/config changes land in volumes)
# =============================================================================
echo ""
echo "==> Re-running seed container..."
docker compose --project-directory "$SERVER_DIR" -f "$COMPOSE_FILE" \
  --profile cloud up --force-recreate --no-deps seed

# =============================================================================
# 8. Seed mod configs into data/config/ (before mc starts)
# =============================================================================
# Platform defaults always overwrite — consumers customise via the overlay,
# not by editing defaults in data/config/. Force-copy ensures every deploy
# gets the latest bundle configs (starter kits, mod settings, etc.).
# This MUST run before mc starts — mods that auto-generate config on first
# boot would otherwise create defaults that block the bundle's version.
echo ""
echo "==> Seeding default mod configs into data/config/..."
BUNDLE_CONFIG="$STACK_DIR/config"
if [[ -d "$BUNDLE_CONFIG" ]]; then
  local_data_cfg="$SERVER_DIR/data/config"
  mkdir -p "$local_data_cfg"
  cd "$BUNDLE_CONFIG"
  find . -type f \
    -not -path './nginx/*' \
    -not -path './uptime-kuma/*' \
    -not -path './cloudflare/*' \
    -not -path './cloudflared/*' \
    -not -name 'modrinth-mods.txt' \
    -not -name 'modrinth-mods.pinned.txt' \
    -not -name 'messages.json' \
    -not -name '1password.env' \
    | while IFS= read -r f; do
      dest="$local_data_cfg/${f#./}"
      mkdir -p "$(dirname "$dest")"
      cp "$f" "$dest"
    done
  cd "$SERVER_DIR"
  echo "  Default configs seeded"
fi

# BlueMap map configs: force-copy from bundle (not skip-if-exists) and
# remove auto-generated duplicates. BlueMap creates its own map configs
# on first boot with names like world_paradise_lost_paradise_lost.conf
# that duplicate our curated paradise_lost.conf. Force-copy ensures our
# names and render bounds are applied; removing extras prevents duplicate
# map entries in the web UI.
BM_BUNDLE="$STACK_DIR/config/bluemap/maps"
BM_DATA="$SERVER_DIR/data/config/bluemap/maps"
if [[ -d "$BM_BUNDLE" && -d "$BM_DATA" ]]; then
  cp "$BM_BUNDLE"/*.conf "$BM_DATA/" 2> /dev/null || true
  for f in "$BM_DATA"/*.conf; do
    [[ -f "$f" ]] || continue
    basename_f="$(basename "$f")"
    if [[ ! -f "$BM_BUNDLE/$basename_f" ]]; then
      rm -f "$f"
      echo "  Removed auto-generated BlueMap map: $basename_f"
    fi
  done
  echo "  BlueMap map configs applied"
fi

# Copy consumer overlay config files to data/config/ (overrides).
# These REPLACE defaults — the consumer's overlay is authoritative.
if [[ -d "$SERVER_DIR/overlay/config" ]]; then
  echo ""
  echo "==> Applying overlay config to data/config/..."
  local_data_cfg="$SERVER_DIR/data/config"
  mkdir -p "$local_data_cfg"
  cd "$SERVER_DIR/overlay/config"
  find . -type f | while IFS= read -r f; do
    dest="$local_data_cfg/${f#./}"
    mkdir -p "$(dirname "$dest")"
    cp "$f" "$dest"
  done
  cd "$SERVER_DIR"
  echo "  Overlay config applied to data/config/"
fi

# Custom datapacks from overlay
if [[ -d "$SERVER_DIR/overlay/config/datapacks" ]]; then
  dp_dir="$SERVER_DIR/data/world/datapacks"
  mkdir -p "$dp_dir"
  for pack in "$SERVER_DIR/overlay/config/datapacks"/*/; do
    [[ -d "$pack" ]] || continue
    pack_name="$(basename "$pack")"
    rm -rf "${dp_dir:?}/${pack_name}"
    cp -r "$pack" "$dp_dir/$pack_name"
  done
  echo "  Custom datapacks synced to world/datapacks/"
fi

# =============================================================================
# 8b. Copy in-house mod JARs to data/mods/ (before mc starts)
# =============================================================================
# MUST run while mc is stopped, before step 11 starts the stack. When this
# ran after the health wait, a jar that broke the boot could never be
# replaced by a deploy (the wait timed out and the script exited first),
# and even healthy deploys only picked up new jars one restart late.
LOCAL_MODS="$STACK_DIR/local-mods"
if [[ -d "$LOCAL_MODS" ]] && ls "$LOCAL_MODS"/*.jar &> /dev/null 2>&1; then
  echo ""
  echo "==> Copying in-house mod JARs..."
  cp "$LOCAL_MODS"/*.jar "$SERVER_DIR/data/mods/"
  # Record what we installed so the stale-jar prune exempts these names.
  for j in "$LOCAL_MODS"/*.jar; do basename "$j"; done > "$SERVER_DIR/data/mods/.local-mods-manifest"
  echo "  Copied $(ls "$LOCAL_MODS"/*.jar | wc -l | tr -d ' ') mod JAR(s)"
fi

# Repair known-bad data inside third-party mod jars (idempotent; a patched
# jar keeps its filename so the MODS_FILE skip-existing download and the
# manifest prune both leave it alone). Currently: Epic Dungeons CamelCase
# loot ids that abort feature placement and spawn lootless chests.
if [[ -f "$SCRIPT_DIR/patch-mod-data.py" ]]; then
  python3 "$SCRIPT_DIR/patch-mod-data.py" "$SERVER_DIR/data/mods" || true
fi

# =============================================================================
# 8c. Enforce single-key config invariants (while mc is stopped)
# =============================================================================
# c2me: the density-function compiler caches compiled+instantiated density
# functions across NoiseConfig creations, ignoring the seed — every custom
# dimension then generates as a clone of the main world. Off restores
# per-dimension worldgen; the rest of c2me stays on. c2me strips the key
# when it rewrites its config at boot, so this re-applies every deploy.
C2ME_TOML="$SERVER_DIR/data/config/c2me.toml"
python3 - "$C2ME_TOML" "[vanillaWorldGenOptimizations]" "useDensityFunctionCompiler" "false" << 'PYEOF'
import sys, os, re
p, section, key, value = sys.argv[1:5]
if os.path.exists(p):
    s = open(p).read()
    if key in s:
        s2 = re.sub(r'%s\s*=\s*\S+' % key, '%s = %s' % (key, value), s)
    elif section.replace("[", "\\[") and section in s:
        s2 = s.replace(section, section + "\n\t%s = %s" % (key, value))
    else:
        s2 = s + "\n%s\n\t%s = %s\n" % (section, key, value)
    if s2 != s:
        open(p, "w").write(s2)
        print("  %s: %s = %s enforced" % (os.path.basename(p), key, value))
else:
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w").write("%s\n\t%s = %s\n" % (section, key, value))
    print("  %s: created with %s = %s" % (os.path.basename(p), key, value))
PYEOF

# Distant Horizons: silence the per-boot G1/explicit-GC nag (multi-line WARN
# wall on every start; the GC choice is deliberate). Keys live under
# [common.logging.warning] in DistantHorizons.toml.
DH_TOML="$SERVER_DIR/data/config/DistantHorizons.toml"
if [[ -f "$DH_TOML" ]]; then
  sed -i \
    -e 's/logGarbageCollectorWarning = true/logGarbageCollectorWarning = false/' \
    -e 's/showGarbageCollectorWarning = true/showGarbageCollectorWarning = false/' \
    -e 's/logExplicitGcDisabledWarning = true/logExplicitGcDisabledWarning = false/' \
    -e 's/showExplicitGcDisabledWarning = true/showExplicitGcDisabledWarning = false/' \
    -e 's/enableDistantGeneration = true/enableDistantGeneration = false/' \
    "$DH_TOML"
  echo "  DH distant generation disabled (restored at deploy end)"
fi

# BlueMap defaults. The config dir is shared with the bluemap sidecar
# container, which reads it at startup — the sidecar is force-recreated
# later in this deploy, so edits made here always take effect.
BLUEMAP_CONF="$SERVER_DIR/data/config/bluemap/core.conf"
if [[ -f "$BLUEMAP_CONF" ]] && grep -q 'accept-download: false' "$BLUEMAP_CONF"; then
  sed -i 's/accept-download: false/accept-download: true/' "$BLUEMAP_CONF"
  echo "  BlueMap: auto-accepted resource download."
fi
BLUEMAP_WEBAPP="$SERVER_DIR/data/config/bluemap/webapp.conf"
if [[ -f "$BLUEMAP_WEBAPP" ]]; then
  sed -i 's/enable-free-flight: true/enable-free-flight: false/' "$BLUEMAP_WEBAPP"
  sed -i 's/default-to-flat-view: false/default-to-flat-view: true/' "$BLUEMAP_WEBAPP"
  if [[ -n "${SPAWN_X:-}" && -n "${SPAWN_Z:-}" ]]; then
    sed -i "s/start-pos: {.*}/start-pos: { x: ${SPAWN_X}, z: ${SPAWN_Z} }/" "$BLUEMAP_WEBAPP"
  fi
  echo "  BlueMap: webapp defaults set (flat view, free-flight off, centred on spawn)."
fi

# =============================================================================
# 9. Enforce Discord integration config (invariant 3)
# =============================================================================
# The dcintegration mod must never register slash commands: it shares the bot
# token with discord-sync and bulk-overwrites the guild command registry on
# every mc boot. discord-sync owns all slash commands.
if [[ -n "${DISCORD_BOT_TOKEN:-}" && -f "$SERVER_DIR/data/config/Discord-Integration.toml" ]]; then
  if ! grep -q '^\[messages' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null; then
    echo "  Discord config is truncated - deleting so the mod regenerates a fresh one"
    rm -f "$SERVER_DIR/data/config/Discord-Integration.toml"
  else
    sed -i "s|botToken = \".*\"|botToken = \"${DISCORD_BOT_TOKEN}\"|" "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    # Game chat <-> Discord sync goes to the CHAT channel when one is set;
    # everything else (bot ops, mod updates, CI notifications) stays on
    # DISCORD_CHANNEL_ID (admin). Falls back to the admin channel so
    # consumers without a dedicated chat channel are unaffected.
    sed -i "s|botChannel = .*|botChannel = ${DISCORD_CHAT_CHANNEL_ID:-${DISCORD_CHANNEL_ID:-0}}|" "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|enable = false|enable = true|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|useServerNameForRcon = false|useServerNameForRcon = true|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|useServerNameForConsole = false|useServerNameForConsole = true|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i "s|serverName = \".*\"|serverName = \"${BRAND_NAME:-Server}\"|" "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|serverStarting = true|serverStarting = false|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    # CRITICAL: [commands] enabled = false (invariant 3)
    sed -i '/^\[commands\]/,/adminRoleIDs/ s|enabled = true|enabled = false|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
  fi
fi
if [[ -f "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" ]]; then
  sed -i 's|^serverStarted = .*|serverStarted = ""|' "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" 2> /dev/null || true
  sed -i 's|^serverStarting = .*|serverStarting = ""|' "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" 2> /dev/null || true
  sed -i 's|^serverStopped = .*|serverStopped = ""|' "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" 2> /dev/null || true
fi

# =============================================================================
# 10. Remove stale mod jars (manifest from the seed's resolver)
# =============================================================================
# The seed container resolves every pin to a URL + filename and writes
# mods-manifest.txt; the mc container's MODS_FILE downloads only missing
# files (no Modrinth API at boot). Removal is our job: delete managed jars
# that are no longer expected. In-house jars from the bundle are exempt.
MANIFEST=$(docker run --rm -v "$(docker volume ls -q | grep stack-mods | head -1)":/m:ro alpine cat /m/mods-manifest.txt 2> /dev/null || echo "")
LOCAL_MANIFEST=$(cat "$SERVER_DIR/data/mods/.local-mods-manifest" 2> /dev/null || echo "")
if [[ -n "$MANIFEST" ]]; then
  echo ""
  echo "==> Pruning stale mod jars..."
  PRUNED=0
  for jar in "$SERVER_DIR"/data/mods/*.jar; do
    [[ -f "$jar" ]] || continue
    base=$(basename "$jar")
    if grep -qxF "$base" <<< "$MANIFEST"; then
      continue
    fi
    if grep -qxF "$base" <<< "$LOCAL_MANIFEST"; then
      continue
    fi
    if [[ -f "$STACK_DIR/local-mods/$base" ]]; then
      continue
    fi
    rm -f "$jar"
    PRUNED=$((PRUNED + 1))
    echo "  pruned: $base"
  done
  echo "  $PRUNED stale jar(s) removed"
fi

# =============================================================================
# 11. Start the stack
# =============================================================================
echo ""
echo "==> Starting stack..."
COMPOSE_CMD="docker compose --project-directory $SERVER_DIR -f $COMPOSE_FILE"

# A mod-sync boot can restart mc once mid-download (Modrinth rate limits),
# which aborts compose's dependency wait even though mc recovers under its
# restart policy. Don't die here - the RCON wait below is the real gate,
# and the second `up -d` after it starts any services compose gave up on.
# shellcheck disable=SC2086
if ! $COMPOSE_CMD --profile cloud up -d --remove-orphans; then
  echo "  compose up reported a dependency failure - mc is likely still"
  echo "  syncing mods; continuing to the health wait."
fi

# Re-apply the autopause suspension inside the freshly (re)created container —
# the pre-restart file died with the old container's filesystem view.
suspend_autopause
# compose up just started mc-backup again — keep it paused until the trap.
pause_backups

# Force-recreate sidecars so config/script changes actually load.
# Keep this list in sync with infra-deploy.sh.
# shellcheck disable=SC2086
$COMPOSE_CMD --profile cloud up -d --force-recreate --no-deps \
  bluemap nav-proxy pack-web cloudflared mod-checker discord-sync idle-tasks 2> /dev/null || true

# Remove any legacy Modrinth override left by pre-v2.12 deploys.
rm -f "$SERVER_DIR/docker-compose.modrinth.yml"

# =============================================================================
# 12. Wait for RCON healthcheck
# =============================================================================
echo ""
echo "==> Waiting for server to pass healthcheck..."

# Boots create every custom dimension world (and any missing mod jars
# download first) — a many-dimension boot regularly exceeds 5 minutes.
MAX_WAIT=600
ELAPSED=0
INTERVAL=10

while [[ $ELAPSED -lt $MAX_WAIT ]]; do
  if server_alive; then
    echo "  Server is healthy (took ${ELAPSED}s)"
    break
  fi
  # Re-assert the autopause suspension each poll: if mc crash-restarted
  # mid-boot (e.g. a failed download), an exec into the dead container
  # was silently lost and the fresh one must get the sentinel again.
  suspend_autopause
  sleep $INTERVAL
  ELAPSED=$((ELAPSED + INTERVAL))
  echo "    ...waiting (${ELAPSED}s / ${MAX_WAIT}s)"
done

if [[ $ELAPSED -ge $MAX_WAIT ]]; then
  echo "  WARNING: Server didn't become ready within ${MAX_WAIT}s."
  echo "  Check logs: docker compose --profile cloud logs -f mc"
  echo "  The whitelist will be restored from .env on next boot."
  exit 1
fi

# Re-assert quiet-boot mode: covers cold boots (mc wasn't alive before the
# stop, so step 4's pre-stop gamerules never ran). Keeps spawning/ticking
# off through dimension activation below; step 14 restores normal rules.
rcon "gamerule doMobSpawning false"
rcon "gamerule randomTickSpeed 0"
rcon "gamerule doDaylightCycle false"
rcon "gamerule doWeatherCycle false"
rcon "gamerule doFireTick false"
echo "  Quiet-boot mode active (spawning/ticking off until deploy completes)"

# Keep non-admins out for the rest of the deploy: the itzg image re-applies
# WHITELIST from .env at boot, so the server is joinable the moment it's
# healthy — hours before a long dimension pass finishes. Empty the list
# again until step 15 restores it; ops bypass the vanilla whitelist, so
# admins can still get in to inspect a live deploy.
if [[ -n "${WHITELIST:-}" ]]; then
  IFS=',' read -ra WL_BOOT_ARRAY <<< "$WHITELIST"
  for player in "${WL_BOOT_ARRAY[@]}"; do
    player="$(echo "$player" | xargs)"
    [[ -n "$player" ]] && rcon "whitelist remove $player" &> /dev/null
  done
fi
rcon "whitelist on"
echo "  Whitelist emptied until deploy completes (ops can still join)"

# =============================================================================
# 13. Start any services that failed the dependency wait
# =============================================================================
# shellcheck disable=SC2086
$COMPOSE_CMD --profile cloud up -d --remove-orphans 2> /dev/null || true
# ...which starts mc-backup yet again — keep it paused until the trap.
pause_backups

# =============================================================================
# 14. World borders + game rules + permissions
# =============================================================================

# PREGEN_BORDER_RADIUS = master radius for tooling (BlueMap, Chunky, DH).
# PLAYER_BORDER_RADIUS = in-game barrier. Defaults to PREGEN_BORDER_RADIUS.
: "${PREGEN_BORDER_RADIUS:=8192}"
: "${PLAYER_BORDER_RADIUS:=${PREGEN_BORDER_RADIUS}}"

# Template BlueMap render bounds from PREGEN_BORDER_RADIUS
BM_NETHER_RADIUS=$((PREGEN_BORDER_RADIUS / 8))
for bm_map in world:$PREGEN_BORDER_RADIUS world_the_nether:$BM_NETHER_RADIUS; do
  bm_file="$SERVER_DIR/data/config/bluemap/maps/${bm_map%%:*}.conf"
  bm_radius="${bm_map##*:}"
  if [[ -f "$bm_file" ]]; then
    sed -i "s/^min-x: .*/min-x: -${bm_radius}/" "$bm_file"
    sed -i "s/^max-x: .*/max-x: ${bm_radius}/" "$bm_file"
    sed -i "s/^min-z: .*/min-z: -${bm_radius}/" "$bm_file"
    sed -i "s/^max-z: .*/max-z: ${bm_radius}/" "$bm_file"
  fi
done
echo "  BlueMap render bounds: overworld +/-${PREGEN_BORDER_RADIUS}, nether +/-${BM_NETHER_RADIUS}"

PLAYER_BORDER_DIAMETER=$((PLAYER_BORDER_RADIUS * 2))
NETHER_PLAYER_RADIUS=$((PLAYER_BORDER_RADIUS / 8))
END_RADIUS=4096
PARADISE_LOST_RADIUS=4096

# Vanilla border (overworld only)
rcon "worldborder center 0 0"
rcon "worldborder set $PLAYER_BORDER_DIAMETER"
echo "  Vanilla border: ${PLAYER_BORDER_DIAMETER} diameter (${PLAYER_BORDER_RADIUS} radius)"

# ChunkyBorder per-dimension borders (idempotent)
rcon "chunky world minecraft:overworld"
rcon "chunky center 0 0"
rcon "chunky radius $PLAYER_BORDER_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder overworld: ${PLAYER_BORDER_RADIUS} radius"

rcon "chunky world minecraft:the_nether"
rcon "chunky center 0 0"
rcon "chunky radius $NETHER_PLAYER_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder nether: ${NETHER_PLAYER_RADIUS} radius (1:8 ratio)"

rcon "chunky world minecraft:the_end"
rcon "chunky center 0 0"
rcon "chunky radius $END_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder end: ${END_RADIUS} radius"

rcon "chunky world paradise_lost:paradise_lost"
rcon "chunky center 0 0"
rcon "chunky radius $PARADISE_LOST_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder paradise lost: ${PARADISE_LOST_RADIUS} radius"

# --- Activate all dimensions (so Chunky can pre-generate them) ----------------
# Dimensions don't create region files until a chunk is loaded in them.
# Forceload one chunk in each, wait for it to save, then remove.
echo ""
echo "==> Activating dimensions for pre-generation..."
for dim in minecraft:the_nether minecraft:the_end paradise_lost:paradise_lost; do
  rcon "execute in $dim run forceload add 0 0"
done
sleep 5
rcon "save-all flush"
sleep 3
for dim in minecraft:the_nether minecraft:the_end paradise_lost:paradise_lost; do
  rcon "execute in $dim run forceload remove 0 0"
done
echo "  Dimensions activated (nether, end, paradise lost)"

# --- Create custom dimensions (idempotent — skips existing) -------------------
# (In-house mod JARs are installed in step 8b, before mc starts.)
if [[ -x "$SCRIPT_DIR/setup-dimensions.sh" && -f "$STACK_DIR/config/dimensions.txt" ]]; then
  echo ""
  echo "==> Creating custom dimensions..."
  bash "$SCRIPT_DIR/setup-dimensions.sh"
fi

# --- Custom dimensions (from dimensions.txt) ----------------------------------
# One-time setup per dimension: load once, set ChunkyBorder, pin BlueMap to
# low-res flat view, then freeze that BlueMap map so it does nothing at all
# until a player actually finds the portal (the mod unfreezes it itself on
# first visit — see DimensionManager.unfreezeBlueMapOnFirstVisit). Gated on
# a marker file, deliberately independent of multiverse_config.json: that
# file just means "the mod knows this dimension exists", not "we've already
# bordered/BlueMap-configured it" — a dimension can be created in one
# deploy and only get this one-time setup in a later one (e.g. this
# rollout, for the ~74 dimensions created before this marker existed).
# Skips comments, blanks, and dimensions sharing the server seed (vanilla worlds).
# These dimensions are meant to sit idle 99.9%+ of the time — idle-tasks
# doesn't pre-generate them, deploy.sh doesn't forceload them, and once
# this one-time setup is done, nothing here ever touches them again.
DIMENSIONS_FILE="$STACK_DIR/config/dimensions.txt"
SETUP_MARKERS_DIR="$SERVER_DIR/data/.dimension-setup"
if [[ -f "$DIMENSIONS_FILE" ]]; then
  mkdir -p "$SETUP_MARKERS_DIR"
  echo ""
  echo "==> Setting up new custom dimensions..."
  BM_MAPS_DIR="$SERVER_DIR/data/config/bluemap/maps"
  NEW_COUNT=0
  SKIPPED_COUNT=0
  # shellcheck disable=SC2034
  while IFS='|' read -r name _type scale seed _portal _ignitor _group _biome _peaceful || [[ -n "$name" ]]; do
    [[ -z "$name" || "$name" = \#* ]] && continue
    [[ "$seed" != "server" && "$seed" = "${SEED:-}" ]] && continue

    if [[ -f "$SETUP_MARKERS_DIR/$name" ]]; then
      SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
      continue
    fi

    rcon "dimension load $name"
    sleep 1
    result=$(timeout 30 docker exec mc rcon-cli "execute in adventure:$name run seed" 2> /dev/null || echo "")
    if [[ -z "$result" || "$result" == *"Unknown"* ]]; then
      echo "    adventure:$name — not ready yet, will retry next deploy"
      continue
    fi

    case "$scale" in
      1) dim_radius=$PLAYER_BORDER_RADIUS ;;
      4) dim_radius=$((PLAYER_BORDER_RADIUS / 4)) ;;
      8) dim_radius=$((PLAYER_BORDER_RADIUS / 8)) ;;
      12) dim_radius=$((PLAYER_BORDER_RADIUS / 12)) ;;
      16) dim_radius=$((PLAYER_BORDER_RADIUS / 16)) ;;
      *) dim_radius=$((PLAYER_BORDER_RADIUS / scale)) ;;
    esac
    rcon "chunky world adventure:$name"
    rcon "chunky center 0 0"
    rcon "chunky radius $dim_radius"
    rcon "chunky shape square"
    rcon "chunky border add"

    if [[ -d "$BM_MAPS_DIR" ]]; then
      for bm_conf in "$BM_MAPS_DIR"/*"$name"*.conf; do
        [[ -f "$bm_conf" ]] || continue
        sed -i 's/enable-hires: true/enable-hires: false/' "$bm_conf"
        sed -i 's/enable-perspective-view: true/enable-perspective-view: false/' "$bm_conf"
        sed -i 's/enable-free-flight-view: true/enable-free-flight-view: false/' "$bm_conf"
      done
    fi
    touch "$SETUP_MARKERS_DIR/$name"
    NEW_COUNT=$((NEW_COUNT + 1))
    echo "    adventure:$name — loaded once, border radius $dim_radius (scale 1:$scale)"
  done < "$DIMENSIONS_FILE"
  echo "  $NEW_COUNT dimension(s) newly configured, $SKIPPED_COUNT already set up (untouched)"
fi

# --- Enforce game rules -------------------------------------------------------
# Also exits quiet-boot mode (step 4 / post-health): spawning, ticking,
# and cycles come back here, at the very end, once dimension work is done.
echo ""
echo "==> Enforcing game rules..."
rcon "gamerule doMobSpawning true"
rcon "gamerule randomTickSpeed 3"
rcon "gamerule doDaylightCycle true"
rcon "gamerule doWeatherCycle true"
rcon "gamerule doFireTick true"
rcon "gamerule doInsomnia false"
rcon "gamerule playersSleepingPercentage 50"
rcon "gamerule spawnRadius 0"
rcon "gamerule forgiveDeadPlayers true"
rcon "gamerule universalAnger false"
rcon "gamerule mobGriefing true"
rcon "gamerule playersNetherPortalDefaultDelay 0"
echo "  Game rules set (quiet-boot mode off)"

# Re-enable DH distant generation (disabled at step 8c to keep its worldgen
# threads from competing with dimension activation and Chunky pregen).
if [[ -f "$DH_TOML" ]]; then
  sed -i 's/enableDistantGeneration = false/enableDistantGeneration = true/' "$DH_TOML"
  rcon "dh config set enableDistantGeneration true" > /dev/null 2>&1 || true
  echo "  DH distant generation re-enabled"
fi

# --- ServerCore hot-reload -----------------------------------------------------
rcon "servercore reload" > /dev/null 2>&1 || true
echo "  ServerCore config reloaded"

# --- Reload datapacks ----------------------------------------------------------
rcon "reload" > /dev/null 2>&1 || true
echo "  Datapacks reloaded"

# --- LuckPerms groups and permissions (idempotent) -----------------------------
if [[ -x "$SCRIPT_DIR/setup-permissions.sh" ]]; then
  echo ""
  echo "==> Setting up permissions..."
  bash "$SCRIPT_DIR/setup-permissions.sh"
fi

# --- Spawn coordinates (betterspawn) -------------------------------------------
if [[ -n "${SPAWN_X:-}" && -n "${SPAWN_Y:-}" && -n "${SPAWN_Z:-}" ]]; then
  rcon "setworldspawn ${SPAWN_X} ${SPAWN_Y} ${SPAWN_Z}"
  echo "  Spawn: ${SPAWN_X} ${SPAWN_Y} ${SPAWN_Z}"
fi

# =============================================================================
# 15. Restore the whitelist
# =============================================================================
echo ""
echo "==> Restoring whitelist..."
if [[ -n "${WHITELIST:-}" ]]; then
  IFS=',' read -ra WL_ARRAY <<< "$WHITELIST"
  for player in "${WL_ARRAY[@]}"; do
    player="$(echo "$player" | xargs)"
    [[ -n "$player" ]] && rcon "whitelist add $player" &> /dev/null
  done
fi
rcon "whitelist on"
echo "  Whitelist restored, connections open"

# =============================================================================
# 16. Welcome back
# =============================================================================
rcon "say $(msg restart.welcome_back)"

# =============================================================================
# 17. Clean up stale Docker resources
# =============================================================================
echo ""
echo "==> Cleaning up old Docker resources..."
docker system prune -f --filter "until=24h" 2> /dev/null || true

# Vanilla writes a debug/chunk-*.txt report for every chunk that fails
# feature placement (e.g. the Epic Dungeons CamelCase loot-id bug) —
# hundreds accumulate under Chunky pregen. Keep 3 days, like the logs.
find "$SERVER_DIR/data/debug" -name 'chunk-*.txt' -mtime +3 -delete 2> /dev/null || true

echo ""
echo "==> Deploy complete."
