#!/usr/bin/env bash
# deploy.sh - The production deploy. Runs ON the server from the stack bundle;
# CI invokes it for every "full" deploy (see deploy-reusable.yml).
#
# Sequence: in-game countdown (60s->1s) -> clear whitelist (blocks joins) ->
# kick all -> save-all flush -> stop mc -> pull images -> re-run seed ->
# seed mod configs into data/config/ -> apply overlay -> datapacks ->
# enforce Discord config -> Modrinth sync IF mod list changed -> compose up ->
# force-recreate sidecars -> wait for RCON (180s) -> world borders ->
# game rules -> LuckPerms -> spawn -> restore whitelist -> BlueMap defaults ->
# welcome back -> docker prune.
#
# Usage:
#   .stack/current/stack/scripts/deploy.sh                    # restart only
#   .stack/current/stack/scripts/deploy.sh --non-interactive  # for CI
#
# The server directory layout (~/server/) is:
#   .env            - generated by CI on every full deploy
#   overlay/        - rsynced from consumer repo by CI
#   cloudflared/    - host-generated tunnel config
#   .stack/current/ - stack bundle cache (via stack-pull.sh)
#   modpack-dist/   - built pack output
#   data/           - world state
#
# Gotchas:
#   - Don't run while CI is deploying (races).
#   - The force-recreate sidecar list below must match infra-deploy.sh.
#   - Game rules here must match config/boring_default_game_rules/config.json.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

# STACK_DIR = the bundle root (where compose files + scripts + config live).
# SERVER_DIR = the server root (where .env, data/, overlay/ live).
STACK_DIR="$PROJECT_DIR"
if [[ "$SCRIPT_DIR" == *"/.stack/"* ]]; then
  SERVER_DIR="${SCRIPT_DIR%%/.stack/*}"
else
  SERVER_DIR="${SERVER_DIR:-$PROJECT_DIR}"
fi
cd "$SERVER_DIR"

COMPOSE_FILE="$STACK_DIR/docker-compose.yml"

# --- load .env ----------------------------------------------------------------
if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

# --- flags --------------------------------------------------------------------
export NON_INTERACTIVE=0
QUICK=0
for arg in "$@"; do
  case "$arg" in
    --non-interactive) export NON_INTERACTIVE=1 ;;
    --quick) QUICK=1 ;;
  esac
done

# --- bind-mount targets -----------------------------------------------------
# These must exist BEFORE any compose command: Docker creates missing
# bind-mount paths as root, so if a sidecar (e.g. mod-checker's read-only
# ./data/mods mount) starts first, mc (uid 1000) can't write its mods and
# crash-loops with AccessDeniedException.
mkdir -p "$SERVER_DIR/data/mods" "$SERVER_DIR/data/config" \
         "$SERVER_DIR/modpack-dist" "$SERVER_DIR/overlay" \
         "$SERVER_DIR/backups" "$SERVER_DIR/cloudflared"

# --- helpers ------------------------------------------------------------------
rcon() {
  docker exec mc rcon-cli "$@" 2> /dev/null || true
}

msg() {
  local key="$1"
  local messages_file="$SERVER_DIR/overlay/config/messages.json"
  [[ -f "$messages_file" ]] || messages_file="$STACK_DIR/config/messages.json"
  python3 -c "import json; print(json.load(open('$messages_file'))['$key'])" 2> /dev/null || echo "$key"
}

server_alive() {
  docker exec mc rcon-cli "list" &> /dev/null 2>&1
}

get_player_count() {
  local result
  result=$(docker exec mc rcon-cli "list" 2> /dev/null || echo "")
  if [[ -z "$result" ]]; then
    echo "0"
    return
  fi
  echo "$result" | grep -oE 'There are [0-9]+' | grep -oE '[0-9]+' || echo "0"
}

# =============================================================================
# 1. In-game countdown warnings
# =============================================================================
if server_alive; then
  if [[ $QUICK -eq 0 ]]; then
    echo "==> Sending in-game restart warnings..."

    rcon "say $(msg restart.warning_60s)"
    echo "  60s warning sent"
    sleep 30

    rcon "say $(msg restart.warning_30s)"
    echo "  30s warning sent"
    sleep 20

    rcon "say $(msg restart.warning_10s)"
    echo "  10s warning sent"
    sleep 5

    rcon "say $(msg restart.warning_5s)"
    sleep 2
    rcon "say $(msg restart.countdown_3)"
    sleep 1
    rcon "say $(msg restart.countdown_2)"
    sleep 1
    rcon "say $(msg restart.countdown_1)"
    sleep 1
  else
    echo "==> Quick restart (skipping countdown)..."
    rcon "say Server restarting now."
    sleep 1
  fi

  # =========================================================================
  # 2. Block new connections
  # =========================================================================
  echo ""
  echo "==> Blocking new connections..."
  rcon "whitelist off"
  rcon "whitelist on"
  echo "  New connections blocked (whitelist cleared)"

  # =========================================================================
  # 3. Kick all connected players
  # =========================================================================
  echo "==> Disconnecting all players..."
  rcon "kick @a $(msg restart.kick)"

  sleep 2

  KICK_WAIT=0
  while [[ $(get_player_count) -gt 0 && $KICK_WAIT -lt 30 ]]; do
    echo "  Waiting for players to disconnect..."
    sleep 2
    KICK_WAIT=$((KICK_WAIT + 2))
  done

  REMAINING=$(get_player_count)
  if [[ "$REMAINING" -gt 0 ]]; then
    echo "  Warning: $REMAINING players still connected after 30s"
    rcon "kick @a $(msg restart.kick_forced)"
    sleep 2
  fi
  echo "  All players disconnected"

  # =========================================================================
  # 4. Save and flush (world is now quiesced)
  # =========================================================================
  echo ""
  echo "==> Saving world..."
  rcon "save-off"
  rcon "save-all flush"
  sleep 5
  echo "  World saved and flushed"

  rcon "save-on"

  # =========================================================================
  # 5. Stop the mc container cleanly
  # =========================================================================
  echo ""
  echo "==> Stopping Minecraft server..."
  docker compose --project-directory "$SERVER_DIR" -f "$COMPOSE_FILE" stop mc 2> /dev/null \
    || docker compose stop mc 2> /dev/null || true
  echo "  Server stopped"

else
  echo "  Server not responding to RCON, skipping warnings/kick."
fi

# =============================================================================
# 6. Pull latest Docker images
# =============================================================================
echo ""
echo "==> Pulling latest Docker images..."
docker compose --project-directory "$SERVER_DIR" -f "$COMPOSE_FILE" --profile cloud pull

# =============================================================================
# 7. Re-run seed container (overlay/config changes land in volumes)
# =============================================================================
echo ""
echo "==> Re-running seed container..."
docker compose --project-directory "$SERVER_DIR" -f "$COMPOSE_FILE" \
  --profile cloud up --force-recreate --no-deps seed

# =============================================================================
# 8. Seed mod configs into data/config/ (before mc starts)
# =============================================================================
# Platform defaults always overwrite — consumers customise via the overlay,
# not by editing defaults in data/config/. Force-copy ensures every deploy
# gets the latest bundle configs (starter kits, mod settings, etc.).
# This MUST run before mc starts — mods that auto-generate config on first
# boot would otherwise create defaults that block the bundle's version.
echo ""
echo "==> Seeding default mod configs into data/config/..."
BUNDLE_CONFIG="$STACK_DIR/config"
if [[ -d "$BUNDLE_CONFIG" ]]; then
  local_data_cfg="$SERVER_DIR/data/config"
  mkdir -p "$local_data_cfg"
  cd "$BUNDLE_CONFIG"
  find . -type f \
    -not -path './nginx/*' \
    -not -path './uptime-kuma/*' \
    -not -path './cloudflare/*' \
    -not -path './cloudflared/*' \
    -not -name 'modrinth-mods.txt' \
    -not -name 'modrinth-mods.pinned.txt' \
    -not -name 'messages.json' \
    -not -name '1password.env' \
    | while IFS= read -r f; do
    dest="$local_data_cfg/${f#./}"
    mkdir -p "$(dirname "$dest")"
    cp "$f" "$dest"
  done
  cd "$SERVER_DIR"
  echo "  Default configs seeded"
fi

# BlueMap map configs: force-copy from bundle (not skip-if-exists) and
# remove auto-generated duplicates. BlueMap creates its own map configs
# on first boot with names like world_paradise_lost_paradise_lost.conf
# that duplicate our curated paradise_lost.conf. Force-copy ensures our
# names and render bounds are applied; removing extras prevents duplicate
# map entries in the web UI.
BM_BUNDLE="$STACK_DIR/config/bluemap/maps"
BM_DATA="$SERVER_DIR/data/config/bluemap/maps"
if [[ -d "$BM_BUNDLE" && -d "$BM_DATA" ]]; then
  cp "$BM_BUNDLE"/*.conf "$BM_DATA/" 2> /dev/null || true
  for f in "$BM_DATA"/*.conf; do
    [[ -f "$f" ]] || continue
    basename_f="$(basename "$f")"
    if [[ ! -f "$BM_BUNDLE/$basename_f" ]]; then
      rm -f "$f"
      echo "  Removed auto-generated BlueMap map: $basename_f"
    fi
  done
  echo "  BlueMap map configs applied"
fi

# Copy consumer overlay config files to data/config/ (overrides).
# These REPLACE defaults — the consumer's overlay is authoritative.
if [[ -d "$SERVER_DIR/overlay/config" ]]; then
  echo ""
  echo "==> Applying overlay config to data/config/..."
  local_data_cfg="$SERVER_DIR/data/config"
  mkdir -p "$local_data_cfg"
  cd "$SERVER_DIR/overlay/config"
  find . -type f | while IFS= read -r f; do
    dest="$local_data_cfg/${f#./}"
    mkdir -p "$(dirname "$dest")"
    cp "$f" "$dest"
  done
  cd "$SERVER_DIR"
  echo "  Overlay config applied to data/config/"
fi

# Custom datapacks from overlay
if [[ -d "$SERVER_DIR/overlay/config/datapacks" ]]; then
  dp_dir="$SERVER_DIR/data/world/datapacks"
  mkdir -p "$dp_dir"
  for pack in "$SERVER_DIR/overlay/config/datapacks"/*/; do
    [[ -d "$pack" ]] || continue
    pack_name="$(basename "$pack")"
    rm -rf "${dp_dir:?}/${pack_name}"
    cp -r "$pack" "$dp_dir/$pack_name"
  done
  echo "  Custom datapacks synced to world/datapacks/"
fi

# =============================================================================
# 9. Enforce Discord integration config (invariant 3)
# =============================================================================
# The dcintegration mod must never register slash commands: it shares the bot
# token with discord-sync and bulk-overwrites the guild command registry on
# every mc boot. discord-sync owns all slash commands.
if [[ -n "${DISCORD_BOT_TOKEN:-}" && -f "$SERVER_DIR/data/config/Discord-Integration.toml" ]]; then
  if ! grep -q '^\[messages' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null; then
    echo "  Discord config is truncated - deleting so the mod regenerates a fresh one"
    rm -f "$SERVER_DIR/data/config/Discord-Integration.toml"
  else
    sed -i "s|botToken = \".*\"|botToken = \"${DISCORD_BOT_TOKEN}\"|" "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i "s|botChannel = .*|botChannel = ${DISCORD_CHANNEL_ID:-0}|" "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|enable = false|enable = true|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|useServerNameForRcon = false|useServerNameForRcon = true|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|useServerNameForConsole = false|useServerNameForConsole = true|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|serverName = ".*"|serverName = "Server"|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    sed -i 's|serverStarting = true|serverStarting = false|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
    # CRITICAL: [commands] enabled = false (invariant 3)
    sed -i '/^\[commands\]/,/adminRoleIDs/ s|enabled = true|enabled = false|' "$SERVER_DIR/data/config/Discord-Integration.toml" 2> /dev/null || true
  fi
fi
if [[ -f "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" ]]; then
  sed -i 's|^serverStarted = .*|serverStarted = ""|' "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" 2> /dev/null || true
  sed -i 's|^serverStarting = .*|serverStarting = ""|' "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" 2> /dev/null || true
  sed -i 's|^serverStopped = .*|serverStopped = ""|' "$SERVER_DIR/data/DiscordIntegration-Data/Messages.toml" 2> /dev/null || true
fi

# =============================================================================
# 10. Sync mods from Modrinth (only if inputs changed)
# =============================================================================
# Hash the mod list inputs (overlay files + stack version) to detect changes.
# A stack version change includes new default mods, so the hash changes.
MODRINTH_OVERRIDE="$SERVER_DIR/docker-compose.modrinth.yml"
MOD_HASH_FILE="$SERVER_DIR/data/.modrinth-hash"
STACK_VER=$(readlink "$SERVER_DIR/.stack/current" 2> /dev/null || echo "unknown")
MOD_INPUTS="${STACK_VER}"
[[ -f "$SERVER_DIR/overlay/mods-extra.txt" ]] && MOD_INPUTS+=$(cat "$SERVER_DIR/overlay/mods-extra.txt")
[[ -f "$SERVER_DIR/overlay/mods-remove.txt" ]] && MOD_INPUTS+=$(cat "$SERVER_DIR/overlay/mods-remove.txt")
CURRENT_MOD_HASH=$(echo "$MOD_INPUTS" | sha256sum | cut -d' ' -f1)
PREVIOUS_MOD_HASH=$(cat "$MOD_HASH_FILE" 2> /dev/null || echo "none")

if [[ "$CURRENT_MOD_HASH" != "$PREVIOUS_MOD_HASH" ]]; then
  echo ""
  echo "==> Mod list changed - enabling Modrinth sync for this restart..."
  cat > "$MODRINTH_OVERRIDE" << 'MODEOF'
services:
  mc:
    environment:
      MODRINTH_PROJECTS: "@/extras/modrinth-mods.txt"
MODEOF
else
  echo ""
  echo "==> Mod list unchanged - skipping Modrinth (fast restart from cached JARs)"
  rm -f "$MODRINTH_OVERRIDE"
fi

# =============================================================================
# 11. Start the stack
# =============================================================================
echo ""
echo "==> Starting stack..."
if [[ -f "$MODRINTH_OVERRIDE" ]]; then
  COMPOSE_CMD="docker compose --project-directory $SERVER_DIR -f $COMPOSE_FILE -f $MODRINTH_OVERRIDE"
else
  COMPOSE_CMD="docker compose --project-directory $SERVER_DIR -f $COMPOSE_FILE"
fi

# A mod-sync boot can restart mc once mid-download (Modrinth rate limits),
# which aborts compose's dependency wait even though mc recovers under its
# restart policy. Don't die here - the RCON wait below is the real gate,
# and the second `up -d` after it starts any services compose gave up on.
# shellcheck disable=SC2086
if ! $COMPOSE_CMD --profile cloud up -d --remove-orphans; then
  echo "  compose up reported a dependency failure - mc is likely still"
  echo "  syncing mods; continuing to the health wait."
fi

# Force-recreate sidecars so config/script changes actually load.
# Keep this list in sync with infra-deploy.sh.
# shellcheck disable=SC2086
$COMPOSE_CMD --profile cloud up -d --force-recreate --no-deps \
  nav-proxy pack-web cloudflared mod-checker discord-sync idle-tasks 2> /dev/null || true

# Clean up the Modrinth override and save the hash
if [[ -f "$MODRINTH_OVERRIDE" ]]; then
  rm -f "$MODRINTH_OVERRIDE"
  echo "$CURRENT_MOD_HASH" > "$MOD_HASH_FILE"
  echo "  Modrinth sync complete - override removed, hash saved"
fi

# =============================================================================
# 12. Wait for RCON healthcheck
# =============================================================================
echo ""
echo "==> Waiting for server to pass healthcheck..."

# Mod-sync boots download ~150 JARs before the server even starts -
# give them a much longer window than a plain restart.
MAX_WAIT=180
[[ "$CURRENT_MOD_HASH" != "$PREVIOUS_MOD_HASH" ]] && MAX_WAIT=600
ELAPSED=0
INTERVAL=10

while [[ $ELAPSED -lt $MAX_WAIT ]]; do
  if server_alive; then
    echo "  Server is healthy (took ${ELAPSED}s)"
    break
  fi
  sleep $INTERVAL
  ELAPSED=$((ELAPSED + INTERVAL))
  echo "    ...waiting (${ELAPSED}s / ${MAX_WAIT}s)"
done

if [[ $ELAPSED -ge $MAX_WAIT ]]; then
  echo "  WARNING: Server didn't become ready within ${MAX_WAIT}s."
  echo "  Check logs: docker compose --profile cloud logs -f mc"
  echo "  The whitelist will be restored from .env on next boot."
  exit 1
fi

# =============================================================================
# 13. Start any services that failed the dependency wait
# =============================================================================
# shellcheck disable=SC2086
$COMPOSE_CMD --profile cloud up -d --remove-orphans 2> /dev/null || true

# =============================================================================
# 14. World borders + game rules + permissions
# =============================================================================

# PREGEN_BORDER_RADIUS = master radius for tooling (BlueMap, Chunky, DH).
# PLAYER_BORDER_RADIUS = in-game barrier. Defaults to PREGEN_BORDER_RADIUS.
: "${PREGEN_BORDER_RADIUS:=8192}"
: "${PLAYER_BORDER_RADIUS:=${PREGEN_BORDER_RADIUS}}"

# Template BlueMap render bounds from PREGEN_BORDER_RADIUS
BM_NETHER_RADIUS=$((PREGEN_BORDER_RADIUS / 8))
for bm_map in world:$PREGEN_BORDER_RADIUS world_the_nether:$BM_NETHER_RADIUS; do
  bm_file="$SERVER_DIR/data/config/bluemap/maps/${bm_map%%:*}.conf"
  bm_radius="${bm_map##*:}"
  if [[ -f "$bm_file" ]]; then
    sed -i "s/^min-x: .*/min-x: -${bm_radius}/" "$bm_file"
    sed -i "s/^max-x: .*/max-x: ${bm_radius}/" "$bm_file"
    sed -i "s/^min-z: .*/min-z: -${bm_radius}/" "$bm_file"
    sed -i "s/^max-z: .*/max-z: ${bm_radius}/" "$bm_file"
  fi
done
echo "  BlueMap render bounds: overworld +/-${PREGEN_BORDER_RADIUS}, nether +/-${BM_NETHER_RADIUS}"

PLAYER_BORDER_DIAMETER=$((PLAYER_BORDER_RADIUS * 2))
NETHER_PLAYER_RADIUS=$((PLAYER_BORDER_RADIUS / 8))
END_RADIUS=4096
PARADISE_LOST_RADIUS=4096

# Vanilla border (overworld only)
rcon "worldborder center 0 0"
rcon "worldborder set $PLAYER_BORDER_DIAMETER"
echo "  Vanilla border: ${PLAYER_BORDER_DIAMETER} diameter (${PLAYER_BORDER_RADIUS} radius)"

# ChunkyBorder per-dimension borders (idempotent)
rcon "chunky world minecraft:overworld"
rcon "chunky center 0 0"
rcon "chunky radius $PLAYER_BORDER_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder overworld: ${PLAYER_BORDER_RADIUS} radius"

rcon "chunky world minecraft:the_nether"
rcon "chunky center 0 0"
rcon "chunky radius $NETHER_PLAYER_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder nether: ${NETHER_PLAYER_RADIUS} radius (1:8 ratio)"

rcon "chunky world minecraft:the_end"
rcon "chunky center 0 0"
rcon "chunky radius $END_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder end: ${END_RADIUS} radius"

rcon "chunky world paradise_lost:paradise_lost"
rcon "chunky center 0 0"
rcon "chunky radius $PARADISE_LOST_RADIUS"
rcon "chunky shape square"
rcon "chunky border add"
echo "  ChunkyBorder paradise lost: ${PARADISE_LOST_RADIUS} radius"

# --- Activate all dimensions (so Chunky can pre-generate them) ----------------
# Dimensions don't create region files until a chunk is loaded in them.
# Forceload one chunk in each, wait for it to save, then remove.
echo ""
echo "==> Activating dimensions for pre-generation..."
for dim in minecraft:the_nether minecraft:the_end paradise_lost:paradise_lost; do
  rcon "execute in $dim run forceload add 0 0"
done
sleep 5
rcon "save-all flush"
sleep 3
for dim in minecraft:the_nether minecraft:the_end paradise_lost:paradise_lost; do
  rcon "execute in $dim run forceload remove 0 0"
done
echo "  Dimensions activated (nether, end, paradise lost)"

# --- Create custom dimensions (idempotent — skips existing) -------------------
if [[ -x "$SCRIPT_DIR/setup-dimensions.sh" && -f "$STACK_DIR/config/dimensions.txt" ]]; then
  echo ""
  echo "==> Creating custom dimensions..."
  bash "$SCRIPT_DIR/setup-dimensions.sh"
fi

# --- Custom dimensions (from dimensions.txt) ----------------------------------
# Handles ~57 modded dimensions: activate, set world borders, enforce BlueMap.
# Skips comments, blanks, and dimensions sharing the server seed (vanilla worlds).
DIMENSIONS_FILE="$STACK_DIR/config/dimensions.txt"
if [[ -f "$DIMENSIONS_FILE" ]]; then
  echo ""
  echo "==> Processing custom dimensions..."

  # Activate custom dimensions (forceload one chunk so region files exist).
  # Dimensions must be created by the custom-dimensions mod first (via
  # setup-dimensions.sh). Skip any that don't exist yet — the mod creates
  # them at runtime, not at deploy time.
  DIM_COUNT=0
  # shellcheck disable=SC2034
  while IFS='|' read -r name _type _scale seed _portal _ignitor _group _biome _peaceful || [[ -n "$name" ]]; do
    [[ -z "$name" || "$name" = \#* ]] && continue
    [[ "$seed" != "server" && "$seed" = "${SEED:-}" ]] && continue
    result=$(docker exec mc rcon-cli "execute in adventure:$name run seed" 2>/dev/null || echo "")
    if [[ -z "$result" || "$result" == *"Unknown"* ]]; then
      continue
    fi
    rcon "execute in adventure:$name run forceload add 0 0"
    DIM_COUNT=$((DIM_COUNT + 1))
  done < "$DIMENSIONS_FILE"

  if [[ $DIM_COUNT -gt 0 ]]; then
    sleep 5
    rcon "save-all flush"
    sleep 3

    # shellcheck disable=SC2034
    while IFS='|' read -r name _type _scale seed _portal _ignitor _group _biome _peaceful || [[ -n "$name" ]]; do
      [[ -z "$name" || "$name" = \#* ]] && continue
      [[ "$seed" != "server" && "$seed" = "${SEED:-}" ]] && continue
      rcon "execute in adventure:$name run forceload remove 0 0"
    done < "$DIMENSIONS_FILE"
    echo "  $DIM_COUNT custom dimensions activated"
  else
    echo "  No custom dimensions created yet (run setup-dimensions.sh first)"
  fi

  # ChunkyBorder per custom dimension (radius scales with dimension scale).
  # Only set borders for dimensions that exist.
  echo "  Setting ChunkyBorder for custom dimensions..."
  # shellcheck disable=SC2034
  while IFS='|' read -r name _type scale seed _portal _ignitor _group _biome _peaceful || [[ -n "$name" ]]; do
    [[ -z "$name" || "$name" = \#* ]] && continue
    [[ "$seed" != "server" && "$seed" = "${SEED:-}" ]] && continue
    result=$(docker exec mc rcon-cli "execute in adventure:$name run seed" 2>/dev/null || echo "")
    if [[ -z "$result" || "$result" == *"Unknown"* ]]; then
      continue
    fi
    case "$scale" in
      1)  dim_radius=$PLAYER_BORDER_RADIUS ;;
      4)  dim_radius=$((PLAYER_BORDER_RADIUS / 4)) ;;
      8)  dim_radius=$((PLAYER_BORDER_RADIUS / 8)) ;;
      12) dim_radius=$((PLAYER_BORDER_RADIUS / 12)) ;;
      16) dim_radius=$((PLAYER_BORDER_RADIUS / 16)) ;;
      *)  dim_radius=$((PLAYER_BORDER_RADIUS / scale)) ;;
    esac
    rcon "chunky world adventure:$name"
    rcon "chunky center 0 0"
    rcon "chunky radius $dim_radius"
    rcon "chunky shape square"
    rcon "chunky border add"
    echo "    adventure:$name — radius $dim_radius (scale 1:$scale)"
  done < "$DIMENSIONS_FILE"

  # BlueMap: custom dimensions get low-res flat view only (saves disk)
  BM_MAPS_DIR="$SERVER_DIR/data/config/bluemap/maps"
  if [[ -d "$BM_MAPS_DIR" ]]; then
    echo "  Enforcing BlueMap settings for custom dimensions..."
    # shellcheck disable=SC2034
    while IFS='|' read -r name _type _scale seed _portal _ignitor _group _biome _peaceful || [[ -n "$name" ]]; do
      [[ -z "$name" || "$name" = \#* ]] && continue
      [[ "$seed" != "server" && "$seed" = "${SEED:-}" ]] && continue
      for bm_conf in "$BM_MAPS_DIR"/*"$name"*.conf; do
        [[ -f "$bm_conf" ]] || continue
        sed -i 's/enable-hires: true/enable-hires: false/' "$bm_conf"
        sed -i 's/enable-perspective-view: true/enable-perspective-view: false/' "$bm_conf"
        sed -i 's/enable-free-flight-view: true/enable-free-flight-view: false/' "$bm_conf"
      done
    done < "$DIMENSIONS_FILE"
    echo "  BlueMap: custom dimensions set to low-res flat view"
  fi
fi

# --- Enforce game rules -------------------------------------------------------
echo ""
echo "==> Enforcing game rules..."
rcon "gamerule doInsomnia false"
rcon "gamerule playersSleepingPercentage 50"
rcon "gamerule spawnRadius 0"
rcon "gamerule forgiveDeadPlayers true"
rcon "gamerule universalAnger false"
rcon "gamerule mobGriefing true"
rcon "gamerule playersNetherPortalDefaultDelay 0"
echo "  Game rules set"

# --- ServerCore hot-reload -----------------------------------------------------
rcon "servercore reload" > /dev/null 2>&1 || true
echo "  ServerCore config reloaded"

# --- Reload datapacks ----------------------------------------------------------
rcon "reload" > /dev/null 2>&1 || true
echo "  Datapacks reloaded"

# --- LuckPerms groups and permissions (idempotent) -----------------------------
if [[ -x "$SCRIPT_DIR/setup-permissions.sh" ]]; then
  echo ""
  echo "==> Setting up permissions..."
  bash "$SCRIPT_DIR/setup-permissions.sh"
fi

# --- Spawn coordinates (betterspawn) -------------------------------------------
if [[ -n "${SPAWN_X:-}" && -n "${SPAWN_Y:-}" && -n "${SPAWN_Z:-}" ]]; then
  rcon "setworldspawn ${SPAWN_X} ${SPAWN_Y} ${SPAWN_Z}"
  echo "  Spawn: ${SPAWN_X} ${SPAWN_Y} ${SPAWN_Z}"
fi

# =============================================================================
# 15. Restore the whitelist
# =============================================================================
echo ""
echo "==> Restoring whitelist..."
if [[ -n "${WHITELIST:-}" ]]; then
  IFS=',' read -ra WL_ARRAY <<< "$WHITELIST"
  for player in "${WL_ARRAY[@]}"; do
    player="$(echo "$player" | xargs)"
    [[ -n "$player" ]] && rcon "whitelist add $player" &> /dev/null
  done
fi
rcon "whitelist on"
echo "  Whitelist restored, connections open"

# --- BlueMap webapp defaults (idempotent) --------------------------------------
BLUEMAP_CONF="$SERVER_DIR/data/config/bluemap/core.conf"
if [[ -f "$BLUEMAP_CONF" ]] && grep -q 'accept-download: false' "$BLUEMAP_CONF"; then
  sed -i 's/accept-download: false/accept-download: true/' "$BLUEMAP_CONF"
  echo "  BlueMap: auto-accepted resource download."
fi

BLUEMAP_WEBAPP="$SERVER_DIR/data/config/bluemap/webapp.conf"
if [[ -f "$BLUEMAP_WEBAPP" ]]; then
  sed -i 's/enable-free-flight: true/enable-free-flight: false/' "$BLUEMAP_WEBAPP"
  sed -i 's/default-to-flat-view: false/default-to-flat-view: true/' "$BLUEMAP_WEBAPP"
  if [[ -n "${SPAWN_X:-}" && -n "${SPAWN_Z:-}" ]]; then
    sed -i "s/start-pos: {.*}/start-pos: { x: ${SPAWN_X}, z: ${SPAWN_Z} }/" "$BLUEMAP_WEBAPP"
  fi
  rcon "bluemap reload" > /dev/null 2>&1 || true
  echo "  BlueMap: webapp defaults set (flat view, free-flight off, centred on spawn)."
fi

# =============================================================================
# 16. Welcome back
# =============================================================================
rcon "say $(msg restart.welcome_back)"

# =============================================================================
# 17. Clean up stale Docker resources
# =============================================================================
echo ""
echo "==> Cleaning up old Docker resources..."
docker system prune -f --filter "until=24h" 2> /dev/null || true

echo ""
echo "==> Deploy complete."
