#!/usr/bin/env python3
"""Require dcintegration's [commands] section to leave slash commands disabled.

Usage: ensure-discord-command-owner.py <Discord-Integration.toml>

The config is generated by a third-party mod. Keep unrelated formatting intact,
but fail before MC starts if the critical command-ownership invariant cannot be
proven from the resulting TOML.
"""

import re
import sys
from pathlib import Path


SECTION_RE = re.compile(r"^\s*\[([^]]+)\]\s*$")
ENABLED_RE = re.compile(r"^(\s*enabled\s*=\s*)(true|false)(\s*(?:#.*)?)$", re.I)


def main() -> int:
    if len(sys.argv) != 2:
        print(f"Usage: {Path(sys.argv[0]).name} <Discord-Integration.toml>", file=sys.stderr)
        return 2

    path = Path(sys.argv[1])
    if not path.is_file():
        print(f"ERROR: Discord integration config not found: {path}", file=sys.stderr)
        return 1

    lines = path.read_text().splitlines(keepends=True)
    in_commands = False
    enabled_count = 0
    changed = False

    for index, line in enumerate(lines):
        section = SECTION_RE.match(line.strip())
        if section:
            in_commands = section.group(1) == "commands"
            continue
        if not in_commands:
            continue
        enabled = ENABLED_RE.match(line.rstrip("\n"))
        if not enabled:
            continue
        enabled_count += 1
        replacement = f"{enabled.group(1)}false{enabled.group(3)}"
        if line.rstrip("\n") != replacement:
            lines[index] = replacement + ("\n" if line.endswith("\n") else "")
            changed = True

    if enabled_count != 1:
        print(
            f"ERROR: expected exactly one [commands] enabled setting, found {enabled_count}",
            file=sys.stderr,
        )
        return 1

    if changed:
        temporary = path.with_name(f".{path.name}.tmp")
        temporary.write_text("".join(lines))
        temporary.replace(path)

    print("Discord command ownership verified: [commands] enabled = false")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
