#!/usr/bin/env python3
"""filter-datapacks.py - strip datapack overrides owned by removed mods.

Purpose:  A structure_set override referencing structures from an absent mod
          fails dynamic-registry load and PREVENTS THE WORLD FROM LOADING —
          so when a consumer removes a default mod via overlay/mods-remove.txt,
          the platform's `structures` datapack must drop that mod's override
          files before mc boots. Platform packs carry an ownership.json
          ({relative file: modrinth slug}, generated by
          gen-structure-presets.py); this script deletes files whose owning
          slug is not in the merged mod list.

Usage:    filter-datapacks.py <datapacks_dir> <defaults_mods_txt> <overlay_dir>
          Called by deploy.sh (step 8) and dev-up.sh after the platform
          datapack sync, BEFORE the overlay datapack sync (overlay packs are
          consumer-owned and never filtered).

Context:  The merged slug set replicates the seed container's semantics:
          defaults minus overlay/mods-remove.txt plus overlay/mods-extra.txt,
          with `datapack:` prefixes stripped and `?` optional markers ignored.
          "minecraft" is always considered present.

Gotchas:  Packs without ownership.json are left untouched. Empty directories
          left behind after filtering are pruned; an override-emptied pack is
          harmless (pack.mcmeta only).
"""

import json
import sys
from pathlib import Path


def slug_of(line):
    entry = line.split("#")[0].strip()
    if not entry:
        return None
    if entry.startswith("datapack:"):
        entry = entry[len("datapack:"):]
    slug = entry.split(":")[0].strip()
    if slug.endswith("?"):
        slug = slug[:-1]
    return slug or None


def read_slugs(path):
    p = Path(path)
    if not p.is_file():
        return set()
    out = set()
    for line in p.read_text().splitlines():
        s = slug_of(line)
        if s:
            out.add(s)
    return out


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    datapacks_dir = Path(sys.argv[1])
    defaults = read_slugs(sys.argv[2])
    overlay = Path(sys.argv[3])
    removed = read_slugs(overlay / "mods-remove.txt")
    extra = read_slugs(overlay / "mods-extra.txt")
    installed = (defaults - removed) | extra | {"minecraft"}

    stripped = 0
    for ownership_file in sorted(datapacks_dir.glob("*/ownership.json")):
        pack_dir = ownership_file.parent
        ownership = json.loads(ownership_file.read_text())
        for rel, slug in ownership.items():
            if slug in installed:
                continue
            target = pack_dir / rel
            if target.is_file():
                target.unlink()
                stripped += 1
                print(f"  filtered {pack_dir.name}/{rel} (mod removed: {slug})")
        # prune emptied directories
        for d in sorted((p for p in pack_dir.rglob("*") if p.is_dir()),
                        key=lambda p: -len(p.parts)):
            try:
                d.rmdir()
            except OSError:
                pass
    if stripped:
        print(f"  {stripped} override file(s) removed for absent mods")


if __name__ == "__main__":
    main()
