#!/usr/bin/env python3
"""Generate the structure group + rarity registry for noise placement.

Purpose:  Classify every known structure set into a noise meta-group
          (deco / settlements / dungeons / landmarks / maritime / endgame /
          loot) and a rarity tier (common / uncommon / rare / endgame), so
          the custom-dimensions mod can build biome-filtered noise pools
          without any per-dimension config.

Context:  Noise structure placement (mods/AGENTS.md § Noise structure
          placement). The two input CSVs are joined because neither is
          sufficient alone — see the header of scripts/data/README.md.

Input:    scripts/data/structure-sets-extracted.csv  (census; regenerated by
            extract-structure-sets.py from the pinned jars — authoritative
            for spacing/separation/frequency/dimension)
          scripts/data/structure-dials.csv           (hand-curated theme —
            authoritative for theme wherever it has a row)

Output:   config/custom-dimensions/structure-groups.json
            Human-readable registry, one entry per set, shipped in the
            stack bundle so consumers can see the classification.
          mods/custom-dimensions/src/main/resources/structure_themes.json
            Jar resource read by StructureThemes. Object form:
            {"<set id>": {"theme": .., "group": .., "rarity": ..}}.
            The loader still accepts the legacy bare-string (theme-only)
            form, so a consumer overlay written against the old shape keeps
            working and only loses group/rarity (both then inferred).

Usage:    scripts/gen-structure-groups.py [--check]
          --check exits 1 if the outputs are stale (CI / pre-release gate)
          rather than rewriting them.

Gotchas:  - This script OWNS structure_themes.json. gen-structure-presets.py
            must never write it as a side effect, or the two would fight —
            the presets run needs network and would revert group/rarity on
            every invocation.
          - Re-run after extract-structure-sets.py, i.e. after any structure
            mod pin bump. It needs no network of its own.
          - The rarity thresholds and the group rules are MIRRORED in
            scripts/seed/structure_placement.py (roller parity, spike task
            F4 requires bit-exact agreement) and consumed by
            StructureThemes.java. Change all three together.
"""

import argparse
import csv
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
EXTRACTED_CSV = REPO / "scripts/data/structure-sets-extracted.csv"
DIALS_CSV = REPO / "scripts/data/structure-dials.csv"
REGISTRY_OUT = REPO / "config/custom-dimensions/structure-groups.json"
THEMES_OUT = REPO / "mods/custom-dimensions/src/main/resources/structure_themes.json"
# Hand-authored (task A2), not generated — but validated and mirrored into the
# jar here so the mod never depends on the config directory being right. The
# worldgen self-containment rule in mods/AGENTS.md: registry data baked into
# the jar is always loaded; data under config/ can be stale, skipped by
# dev-up.sh's skip-if-exists, or reverted by a seed run.
TYPE_DEFAULTS_SRC = REPO / "config/custom-dimensions/structure-type-defaults.json"
TYPE_DEFAULTS_OUT = REPO / "mods/custom-dimensions/src/main/resources/structure_type_defaults.json"

# The six hand-curated themes, plus the extracted CSV's extra "ruins" bucket
# which has no separate noise behaviour — ruins ARE environmental detail.
THEME_TO_GROUP = {
    "deco": "deco",
    "ruins": "deco",
    "settlement": "settlements",
    "dungeon": "dungeons",
    "landmark": "landmarks",
    "maritime": "maritime",
    "loot": "loot",
}
GROUPS = ("deco", "settlements", "dungeons", "landmarks", "maritime", "endgame", "loot")
RARITIES = ("common", "uncommon", "rare", "endgame")

# Lifted verbatim from extract-structure-sets.py's ENDGAME_PATTERNS: an
# already-reviewed "flagship content" keyword list. Used here to pick the
# endgame GROUP (mega-dungeons), never the rarity tier.
ENDGAME_KEYWORDS = re.compile(
    r"ancient_city|mansion|woodland|coliseum|sanctum|mega.*fortress|"
    r"trial_chambers|mega_ship|mega_dungeon|stronghold|"
    r"boss|climax|arena|typhon|heavenly_conqueror|"
    r"heavenly_rider|ceryneian|flying_dutchman|"
    r"forbidden_castle|shiraz_palace|plague_asylum|"
    r"large_dungeon|citadel", re.I)

# Only these themes may be promoted to the endgame group. Without the gate a
# decorative "small_arena" or a "citadel_house" settlement would be promoted
# by a keyword that describes its name, not its role.
ENDGAME_ELIGIBLE_THEMES = {"dungeon", "landmark", "maritime"}

# ...and only at these rarity tiers. The endgame group means "the big prize
# you journey to", and its default profile pushes it to the outer ring. A set
# the mod itself tuned to appear every 16 chunks is not that, whatever it is
# called: friendsandfoes:citadel (sp=16), minecraft:ancient_cities (sp=24) and
# minecraft:trial_chambers (sp=34) all match the keyword list and all stay in
# `dungeons`. An author who disagrees promotes the tier per-dimension with
# structures.rarity, which moves the group with it.
ENDGAME_ELIGIBLE_RARITIES = {"rare", "endgame"}

# The dials CSV only ever covered sets gen-structure-presets.py might retune,
# so it skips vanilla (bar villages) and a few mods entirely. The extracted
# CSV's theme is a first-match-wins regex with `landmark` as its catch-all —
# fine as a signal, wrong often enough to matter for exactly these sets, which
# are also the ones the spike's regression checks name. Hand-reviewed:
#   set id -> (theme, dimension|None)
# `dimension` is corrected only where inference is plainly wrong (it keys off
# the mod jar and structure names, so paradise_lost reads as overworld and
# ruined_portals reads as nether off its `_nether` variant).
CURATED = {
    # --- vanilla -----------------------------------------------------------
    # Explorable temples with loot and traps: landmarks, not scenery.
    "minecraft:desert_pyramids": ("landmark", "overworld"),
    "minecraft:jungle_temples": ("landmark", "overworld"),
    "minecraft:igloos": ("landmark", "overworld"),
    # Small scattered detail.
    "minecraft:trail_ruins": ("deco", "overworld"),
    "minecraft:nether_fossils": ("deco", "nether"),
    # Regex matched the `_ocean` variant and called the whole set maritime.
    "minecraft:ruined_portals": ("deco", "overworld"),
    "minecraft:ocean_ruins": ("maritime", "overworld"),
    "minecraft:ocean_monuments": ("maritime", "overworld"),
    "minecraft:swamp_huts": ("settlement", "overworld"),
    "minecraft:mineshafts": ("dungeon", "overworld"),
    # Regex matched "buried" in the dungeon rule; it is a loot cache.
    "minecraft:buried_treasures": ("loot", "overworld"),
    # concentric_rings placement — never enters a noise pool (C2 checks the
    # live placement class), classified for completeness only.
    "minecraft:strongholds": ("dungeon", "overworld"),
    # --- paradise_lost -----------------------------------------------------
    "paradise_lost:aurel_tower": ("landmark", "paradise_lost"),
    "paradise_lost:birdcage": ("landmark", "paradise_lost"),
    "paradise_lost:palace": ("landmark", "paradise_lost"),
    "paradise_lost:remains": ("deco", "paradise_lost"),
    "paradise_lost:vault": ("dungeon", "paradise_lost"),
    # --- friends & foes ----------------------------------------------------
    # All four are hostile illager sites, not scenery.
    "friendsandfoes:citadel": ("dungeon", "overworld"),
    "friendsandfoes:iceologer_cabin": ("dungeon", "overworld"),
    "friendsandfoes:illusioner_shack": ("dungeon", "overworld"),
    "friendsandfoes:illusioner_training_grounds": ("dungeon", "overworld"),
    # --- supplementaries ---------------------------------------------------
    "supplementaries:galleons": ("maritime", "overworld"),
    "supplementaries:road_signs": ("deco", "overworld"),
}

# The extracted CSV's `dimensions` and the dials CSV's `dims` use different
# vocabularies for the same idea. Normalise to the mod's world-type families.
DIMENSION_ALIASES = {
    "overworld": "overworld",
    "sky+overworld": "overworld",
    "nether": "nether",
    "end": "end",
}


def rarity_for(spacing):
    """Spacing -> rarity tier. Spacing-only by design (spike A1 prose).

    MIRRORED in scripts/seed/structure_placement.py and consumed by
    StructureThemes.java — change all three together.
    """
    if spacing is None:
        return None
    if spacing > 80:
        return "endgame"
    if spacing > 45:
        return "rare"
    if spacing > 24:
        return "uncommon"
    return "common"


def group_for(theme, rarity, set_id, structures):
    """Theme + rarity + id/structure names -> noise meta-group.

    MIRRORED in scripts/seed/structure_placement.py — change both together.
    """
    group = THEME_TO_GROUP.get(theme)
    if group is None:
        return None
    if theme in ENDGAME_ELIGIBLE_THEMES and rarity in ENDGAME_ELIGIBLE_RARITIES:
        haystack = set_id + " " + (structures or "")
        if ENDGAME_KEYWORDS.search(haystack):
            return "endgame"
    return group


def parse_dials_spacing(current):
    """dials `current` column ("34/8", "27/12 f=0.5", "/") -> spacing|None."""
    m = re.match(r"^\s*(\d+)/(\d+)", current or "")
    return int(m.group(1)) if m else None


def load_extracted():
    rows = {}
    with open(EXTRACTED_CSV, newline="") as fh:
        for r in csv.DictReader(fh):
            set_id = r["structure_set_id"].strip()
            if ":" not in set_id:
                continue
            try:
                spacing = int(r["spacing"])
            except (TypeError, ValueError):
                spacing = None
            try:
                frequency = float(r["frequency"])
            except (TypeError, ValueError):
                frequency = 1.0
            rows[set_id] = {
                "theme": r["theme"].strip(),
                "structures": r["structures"],
                "spacing": spacing,
                "separation": _int_or_none(r["separation"]),
                "frequency": frequency,
                "dimension": DIMENSION_ALIASES.get(r["dimensions"].strip()),
                "source": r["mod_source"],
            }
    return rows


def load_dials():
    rows = {}
    with open(DIALS_CSV, newline="") as fh:
        for r in csv.DictReader(fh):
            set_id = r["structure_set"].strip()
            # Marker rows carry a parenthetical note instead of a set name
            # (e.g. "dungeons_reborn:(placed features)" — that mod ships no
            # structure sets at all).
            if ":" not in set_id or "(" in set_id:
                continue
            rows[set_id] = {
                "theme": r["theme"].strip(),
                "structures": r["structures"],
                "spacing": parse_dials_spacing(r["current"]),
                "dimension": DIMENSION_ALIASES.get(r["dims"].strip()),
                "source": r["mod"],
            }
    return rows


def _int_or_none(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def build():
    extracted = load_extracted()
    dials = load_dials()
    registry = {}
    warnings = []

    for set_id in sorted(set(extracted) | set(dials)):
        ext = extracted.get(set_id)
        dia = dials.get(set_id)
        # set_id came from the union, so at least one row always exists.
        primary = dia or ext
        assert primary is not None

        # Theme precedence: curated override > hand-curated dials row >
        # extracted regex. The extracted theme is first-match-wins with
        # `landmark` as its catch-all default, so it is a fallback, not a peer.
        curated = CURATED.get(set_id)
        if curated:
            theme, curated_dimension = curated
            theme_source = "curated"
        else:
            theme = primary["theme"]
            theme_source = "dials" if dia else "extracted"
            curated_dimension = None

        # Spacing: the extracted census reads it from the pinned jar.
        spacing = None
        if ext and ext["spacing"] is not None:
            spacing = ext["spacing"]
        elif dia and dia["spacing"] is not None:
            spacing = dia["spacing"]

        census = ext or dia
        assert census is not None
        structures = census.get("structures") or ""
        rarity = rarity_for(spacing)
        if rarity is None:
            warnings.append("%s: no spacing in either CSV — rarity defaulted to uncommon" % set_id)
            rarity = "uncommon"
        group = group_for(theme, rarity, set_id, structures)
        if group is None:
            warnings.append("%s: unknown theme %r — no group assigned" % (set_id, theme))
            continue

        entry = {
            "theme": theme,
            "group": group,
            "rarity": rarity,
            "spacing": spacing,
            "themeSource": theme_source,
        }
        if ext:
            entry["separation"] = ext["separation"]
            entry["frequency"] = ext["frequency"]
        dimension = curated_dimension or census.get("dimension")
        if dimension:
            entry["dimension"] = dimension
        entry["source"] = census.get("source")
        registry[set_id] = entry

    return registry, warnings


def render_registry(registry):
    counts_group = {}
    counts_rarity = {}
    for e in registry.values():
        counts_group[e["group"]] = counts_group.get(e["group"], 0) + 1
        counts_rarity[e["rarity"]] = counts_rarity.get(e["rarity"], 0) + 1
    doc = {
        "_comment": (
            "Generated by scripts/gen-structure-groups.py — do not hand-edit. "
            "Structure-set id -> noise meta-group and rarity tier. "
            "Consumers override per-dimension via structures.rarity, or add "
            "their own mods' sets via overlay/config/structure_themes.json."
        ),
        "_counts": {
            "sets": len(registry),
            "byGroup": dict(sorted(counts_group.items())),
            "byRarity": dict(sorted(counts_rarity.items())),
        },
        "groups": list(GROUPS),
        "rarities": list(RARITIES),
        "sets": dict(sorted(registry.items())),
    }
    return json.dumps(doc, indent=1) + "\n"


def render_themes(registry):
    """Jar resource: the mod's runtime lookup table, minus audit-only fields."""
    out = {}
    for set_id, e in sorted(registry.items()):
        out[set_id] = {"theme": e["theme"], "group": e["group"], "rarity": e["rarity"]}
    return json.dumps(out, indent=1) + "\n"


def _strip_comments(node: Any) -> Any:
    """Drop every _comment key, recursively — the jar copy is machine-read."""
    if isinstance(node, dict):
        return {k: _strip_comments(v) for k, v in node.items()
                if not k.startswith("_")}
    if isinstance(node, list):
        return [_strip_comments(v) for v in node]
    return node


def _section(doc: dict, key: str) -> dict:
    """doc[key] as a dict, with a clear error instead of a TypeError."""
    value = doc.get(key)
    if not isinstance(value, dict):
        raise SystemExit("structure-type-defaults.json: %r must be an object" % key)
    return value


def render_type_defaults():
    """Jar copy of the hand-authored type-defaults, validated on the way through.

    Validation here rather than only in the unit test, so that regenerating
    after a hand-edit fails loudly instead of baking a broken file into the
    jar (an unresolvable group or curve name is a silent fallback at boot).
    """
    doc = json.loads(TYPE_DEFAULTS_SRC.read_text())
    stripped: dict = _strip_comments(doc)

    curves = _section(stripped, "curves")
    known_groups = set(GROUPS)
    profiles = {"natural", "dense", "sparse", "cluster", "none"}
    errors = []

    for name, curve in curves.items():
        if len(curve) != 10:
            errors.append("curve %s has %d points, expected 10" % (name, len(curve)))
        if any(not isinstance(v, (int, float)) or v < 0.0 or v > 3.0 for v in curve):
            errors.append("curve %s has a value outside 0.0-3.0" % name)

    group_defaults = _section(stripped, "groupDefaults")
    for group, cfg in group_defaults.items():
        if group not in known_groups:
            errors.append("groupDefaults has unknown group %s" % group)
        if cfg.get("profile") not in profiles:
            errors.append("group %s has unknown profile %r" % (group, cfg.get("profile")))
        if cfg.get("radial") not in curves:
            errors.append("group %s has unknown curve %r" % (group, cfg.get("radial")))
    missing = known_groups - set(group_defaults)
    if missing:
        errors.append("groupDefaults missing: %s" % ", ".join(sorted(missing)))

    if set(_section(stripped, "rarityShares")) != set(RARITIES):
        errors.append("rarityShares must cover exactly %s" % ", ".join(RARITIES))

    for type_name, cfg in _section(stripped, "types").items():
        enabled = set(cfg.get("groups") or [])
        unknown = enabled - known_groups
        if unknown:
            errors.append("type %s enables unknown group(s) %s"
                          % (type_name, ", ".join(sorted(unknown))))
        for group, profile in (cfg.get("profiles") or {}).items():
            if group not in enabled:
                errors.append("type %s sets a profile for disabled group %s"
                              % (type_name, group))
            if profile not in profiles:
                errors.append("type %s has unknown profile %r" % (type_name, profile))
        for group, curve in (cfg.get("radial") or {}).items():
            if group not in enabled:
                errors.append("type %s sets a radial curve for disabled group %s"
                              % (type_name, group))
            if curve not in curves:
                errors.append("type %s has unknown curve %r" % (type_name, curve))

    shifts = _section(stripped, "difficultyShifts")
    for key, field, valid in (("hostile", "radial", curves),
                              ("peaceful", "profiles", profiles)):
        for group, value in (shifts[key].get(field) or {}).items():
            if group not in known_groups:
                errors.append("difficultyShifts.%s references unknown group %s"
                              % (key, group))
            if value not in valid:
                errors.append("difficultyShifts.%s.%s has unknown value %r"
                              % (key, group, value))

    if errors:
        raise SystemExit("structure-type-defaults.json is invalid:\n  "
                         + "\n  ".join(errors))

    return json.dumps(stripped, indent=1) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the outputs are stale instead of rewriting")
    args = ap.parse_args()

    registry, warnings = build()
    for w in warnings:
        print("  WARNING: " + w, file=sys.stderr)

    outputs = {
        REGISTRY_OUT: render_registry(registry),
        THEMES_OUT: render_themes(registry),
        TYPE_DEFAULTS_OUT: render_type_defaults(),
    }

    stale = []
    for path, body in outputs.items():
        current = path.read_text() if path.exists() else None
        if current != body:
            stale.append(path)

    if args.check:
        if stale:
            for p in stale:
                print("STALE: %s" % p.relative_to(REPO), file=sys.stderr)
            print("Run scripts/gen-structure-groups.py to regenerate.", file=sys.stderr)
            return 1
        print("structure group registry up to date (%d sets)" % len(registry))
        return 0

    for path, body in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
        print("wrote %s" % path.relative_to(REPO))
    print("%d sets classified" % len(registry))
    return 0


if __name__ == "__main__":
    sys.exit(main())
