#!/usr/bin/env bash
# op-env.sh - Generate a .env file from 1Password + committed config.
#
# Merges .env.example (committed, non-secret) with secrets from
# 1Password (via op:// references in config/1password.env).
#
# Usage:
#   ./scripts/op-env.sh              # local environment (default)
#   ./scripts/op-env.sh prod         # production environment
#   ./scripts/op-env.sh local > .env # write to .env file
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${CONSUMER_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"

ENV_NAME="${1:-local}"
SERVER_ENV="$PROJECT_DIR/.env.example"
OP_TEMPLATE="$PROJECT_DIR/config/1password.env"

# Per-server 1Password item (matches op-sync-env.sh). BRAND_SLUG comes from
# an existing .env when present; on a fresh machine pass it explicitly:
#   OP_ITEM_NAME="Minecraft Server - myslug" ./scripts/op-env.sh > .env
if [[ -z "${BRAND_SLUG:-}" && -f "$PROJECT_DIR/.env" ]]; then
  BRAND_SLUG=$(grep -E '^BRAND_SLUG=' "$PROJECT_DIR/.env" | head -1 | cut -d= -f2- | tr -d "'\"") || true
fi
ITEM_NAME="${OP_ITEM_NAME:-Minecraft Server${BRAND_SLUG:+ - ${BRAND_SLUG}}}"

# --- check prerequisites ------------------------------------------------------
if ! command -v op &> /dev/null; then
  echo "1Password CLI (op) not found." >&2
  echo "  macOS:  brew install 1password-cli" >&2
  echo "  Other:  https://developer.1password.com/docs/cli/get-started/" >&2
  echo "Or manually create .env from .env.example instead." >&2
  exit 1
fi

if ! op account list &> /dev/null 2>&1; then
  echo "Not signed in to 1Password. Run: op signin" >&2
  exit 1
fi

echo "# Generated by op-env.sh (environment: ${ENV_NAME})" >&2
echo "# $(date '+%Y-%m-%d %H:%M:%S')" >&2
echo "" >&2

# --- emit committed config first ---------------------------------------------
echo "# === Committed config (from .env.example) ==="
grep -v '^\s*#' "$SERVER_ENV" | grep -v '^\s*$'
echo ""

# --- emit instance overrides if present --------------------------------------
if [[ -f "$LOCAL_ENV" ]]; then
  grep -v '^\s*#' "$LOCAL_ENV" | grep -v '^\s*$'
  echo ""
fi

# --- resolve 1Password secrets -----------------------------------------------
echo "# === Secrets (from 1Password) ==="

# Export MC_ENV so the op:// references can use it
export MC_ENV="$ENV_NAME"

while IFS= read -r line; do
  # Skip comments and blank lines
  [[ "$line" =~ ^[[:space:]]*# ]] && continue
  [[ -z "${line// /}" ]] && continue

  # Extract VAR_NAME=op://...
  var_name="${line%%=*}"
  op_ref="${line#*=}"

  # Resolve the op:// reference - substitute MC_ENV and the per-brand item name
  op_ref="${op_ref//\$\{MC_ENV:-local\}/$ENV_NAME}"
  op_ref="${op_ref/Minecraft Server/$ITEM_NAME}"

  # Read from 1Password
  value=$(op read "$op_ref" 2> /dev/null || true)

  if [[ -n "$value" ]]; then
    echo "${var_name}=${value}"
    echo "  ✓ ${var_name}" >&2
  else
    echo "# ${var_name}= (not found in 1Password: ${op_ref})"
    echo "  ✗ ${var_name} - not found at ${op_ref}" >&2
  fi
done < "$OP_TEMPLATE"

# --- add environment-specific overrides ---------------------------------------
echo ""
echo "# === Environment: ${ENV_NAME} ==="
if [[ "$ENV_NAME" == "local" ]]; then
  echo "ONLINE_MODE=FALSE"
  echo "MEMORY=4G"
else
  echo "ONLINE_MODE=TRUE"
fi

echo "" >&2
echo "Done. Pipe to .env: $0 ${ENV_NAME} > .env" >&2
