#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 02 00:13:35 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
